-- +goose Up
-- Set for passwords generated by an admin: the user must choose their own
-- password before they can do anything else.
ALTER TABLE users ADD COLUMN must_change_password BOOLEAN NOT NULL DEFAULT FALSE;

-- +goose Down
ALTER TABLE users DROP COLUMN must_change_password;
