// Package store persists accounts, folders and message metadata in
// PostgreSQL.
package store

import (
	"context"
	"database/sql"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"math"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"

	"github.com/pklnx/mail-archive/internal/store/db"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

// ErrNotFound is returned when a record does not exist.
var ErrNotFound = errors.New("not found")

// ErrConflict is returned when a unique constraint is violated.
var ErrConflict = errors.New("already exists")

// Store wraps a PostgreSQL connection pool. Queries are generated by sqlc
// from internal/store/queries (see sqlc.yaml).
type Store struct {
	pool *pgxpool.Pool
	q    *db.Queries
}

// Open connects to the database.
func Open(ctx context.Context, url string) (*Store, error) {
	pool, err := pgxpool.New(ctx, url)
	if err != nil {
		return nil, err
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("connect to database: %w", err)
	}
	return &Store{pool: pool, q: db.New(pool)}, nil
}

// Close releases all connections.
func (s *Store) Close() { s.pool.Close() }

// Migrate applies all pending schema migrations.
func (s *Store) Migrate(ctx context.Context) ([]string, error) {
	var applied []string
	err := s.withMigrations(func(p *goose.Provider) error {
		results, err := p.Up(ctx)
		for _, r := range results {
			applied = append(applied, r.Source.Path)
		}
		return err
	})
	return applied, err
}

// MigrateDown rolls back the most recently applied migration. This usually
// drops data. It returns the migration that was rolled back.
func (s *Store) MigrateDown(ctx context.Context) (string, error) {
	var rolledBack string
	err := s.withMigrations(func(p *goose.Provider) error {
		r, err := p.Down(ctx)
		if errors.Is(err, goose.ErrNoNextVersion) {
			return errors.New("no migration to roll back")
		}
		if err != nil {
			return err
		}
		rolledBack = r.Source.Path
		return nil
	})
	return rolledBack, err
}

// MigrationStatus describes one known migration.
type MigrationStatus struct {
	Path      string
	Applied   bool
	AppliedAt time.Time
}

// MigrationStatus lists all migrations and whether they are applied.
func (s *Store) MigrationStatus(ctx context.Context) ([]MigrationStatus, error) {
	var out []MigrationStatus
	err := s.withMigrations(func(p *goose.Provider) error {
		statuses, err := p.Status(ctx)
		if err != nil {
			return err
		}
		for _, st := range statuses {
			out = append(out, MigrationStatus{
				Path:      st.Source.Path,
				Applied:   st.State == goose.StateApplied,
				AppliedAt: st.AppliedAt,
			})
		}
		return nil
	})
	return out, err
}

func (s *Store) withMigrations(fn func(*goose.Provider) error) error {
	sub, err := fs.Sub(migrationsFS, "migrations")
	if err != nil {
		return err
	}
	sqlDB := stdlib.OpenDBFromPool(s.pool)
	defer func(d *sql.DB) { _ = d.Close() }(sqlDB)
	provider, err := goose.NewProvider(goose.DialectPostgres, sqlDB, sub)
	if err != nil {
		return err
	}
	return fn(provider)
}

// TLSMode describes how to secure the IMAP connection.
type TLSMode string

// Supported TLS modes.
const (
	TLSModeTLS      TLSMode = "tls"      // implicit TLS (port 993)
	TLSModeSTARTTLS TLSMode = "starttls" // STARTTLS upgrade (port 143)
	TLSModeNone     TLSMode = "none"     // plaintext, only for local testing
)

// Account is an IMAP mailbox to archive.
type Account struct {
	ID              int64
	Name            string
	Host            string
	Port            int
	TLSMode         TLSMode
	Username        string
	PasswordEnc     []byte
	IncludedFolders []string // empty means all folders
	ExcludedFolders []string
	Enabled         bool
	CreatedAt       time.Time
	// RemovedAt is set for removed accounts: their archived mail stays, but
	// they have no password and are never synced.
	RemovedAt *time.Time
}

func accountFromDB(r db.Account) *Account {
	return &Account{
		ID:              r.ID,
		Name:            r.Name,
		Host:            r.Host,
		Port:            int(r.Port),
		TLSMode:         TLSMode(r.TlsMode),
		Username:        r.Username,
		PasswordEnc:     r.PasswordEnc,
		IncludedFolders: r.IncludedFolders,
		ExcludedFolders: r.ExcludedFolders,
		Enabled:         r.Enabled,
		CreatedAt:       r.CreatedAt,
		RemovedAt:       r.RemovedAt,
	}
}

// CreateAccount inserts a new account and sets its ID.
func (s *Store) CreateAccount(ctx context.Context, a *Account) error {
	if a.IncludedFolders == nil {
		a.IncludedFolders = []string{}
	}
	if a.ExcludedFolders == nil {
		a.ExcludedFolders = []string{}
	}
	if a.Port < 1 || a.Port > 65535 {
		return fmt.Errorf("invalid port %d", a.Port)
	}
	row, err := s.q.CreateAccount(ctx, db.CreateAccountParams{
		Name:            a.Name,
		Host:            a.Host,
		Port:            int32(a.Port), //nolint:gosec // range checked above
		TlsMode:         string(a.TLSMode),
		Username:        a.Username,
		PasswordEnc:     a.PasswordEnc,
		IncludedFolders: a.IncludedFolders,
		ExcludedFolders: a.ExcludedFolders,
		Enabled:         a.Enabled,
	})
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == "23505" {
		return fmt.Errorf("account %q: %w", a.Name, ErrConflict)
	}
	if err != nil {
		return err
	}
	a.ID, a.CreatedAt = row.ID, row.CreatedAt
	return nil
}

// UpdatePassword replaces an account's encrypted password.
func (s *Store) UpdatePassword(ctx context.Context, id int64, passwordEnc []byte) error {
	return one(s.q.UpdatePassword(ctx, db.UpdatePasswordParams{ID: id, PasswordEnc: passwordEnc}))
}

// SetAccountEnabled enables or disables an account.
func (s *Store) SetAccountEnabled(ctx context.Context, id int64, enabled bool) error {
	return one(s.q.SetAccountEnabled(ctx, db.SetAccountEnabledParams{ID: id, Enabled: enabled}))
}

// SetFolderFilters replaces the include and exclude folder lists.
func (s *Store) SetFolderFilters(ctx context.Context, id int64, included, excluded []string) error {
	if included == nil {
		included = []string{}
	}
	if excluded == nil {
		excluded = []string{}
	}
	return one(s.q.SetFolderFilters(ctx, db.SetFolderFiltersParams{
		ID: id, IncludedFolders: included, ExcludedFolders: excluded,
	}))
}

// UpdateConnection replaces the server settings and encrypted password.
func (s *Store) UpdateConnection(ctx context.Context, a *Account) error {
	if a.Port < 1 || a.Port > 65535 {
		return fmt.Errorf("invalid port %d", a.Port)
	}
	return one(s.q.UpdateAccountConnection(ctx, db.UpdateAccountConnectionParams{
		ID: a.ID, Host: a.Host, Port: int32(a.Port), //nolint:gosec // range checked above
		TlsMode: string(a.TLSMode), Username: a.Username, PasswordEnc: a.PasswordEnc,
	}))
}

// RemoveResult tells how DeleteOrRemoveAccount handled an account.
type RemoveResult string

// Possible outcomes of DeleteOrRemoveAccount.
const (
	AccountDeleted RemoveResult = "deleted" // no archived mail: the account is gone
	AccountRemoved RemoveResult = "removed" // archived mail kept, credentials wiped
)

// DeleteOrRemoveAccount deletes an account without archived mail. An account
// with archived mail is marked as removed instead: its mail stays searchable
// and keeps showing where it came from, but the password is wiped and the
// account is never synced again.
func (s *Store) DeleteOrRemoveAccount(ctx context.Context, id int64) (RemoveResult, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return "", err
	}
	defer func() { _ = tx.Rollback(ctx) }()
	q := s.q.WithTx(tx)
	n, err := q.CountAccountLocations(ctx, id)
	if err != nil {
		return "", err
	}
	result := AccountRemoved
	if n == 0 {
		result = AccountDeleted
		if err := q.DeleteAccountFolders(ctx, id); err != nil {
			return "", err
		}
		err = one(q.DeleteAccount(ctx, id))
	} else {
		err = one(q.RemoveAccount(ctx, id))
	}
	if err != nil {
		return "", err
	}
	return result, tx.Commit(ctx)
}

// GetAccount looks up an account by ID.
func (s *Store) GetAccount(ctx context.Context, id int64) (*Account, error) {
	r, err := s.q.GetAccount(ctx, id)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return accountFromDB(r), nil
}

// GetAccountByName looks up an account by its unique name.
func (s *Store) GetAccountByName(ctx context.Context, name string) (*Account, error) {
	r, err := s.q.GetAccountByName(ctx, name)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return accountFromDB(r), nil
}

// ListAccounts returns all accounts ordered by name.
func (s *Store) ListAccounts(ctx context.Context) ([]*Account, error) {
	rows, err := s.q.ListAccounts(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*Account, 0, len(rows))
	for _, r := range rows {
		out = append(out, accountFromDB(r))
	}
	return out, nil
}

// Folder is the sync state of one IMAP folder.
type Folder struct {
	ID          int64
	AccountID   int64
	Name        string
	UIDValidity uint32
	LastUID     uint32
}

// GetOrCreateFolder returns the sync state for a folder, creating it if new.
func (s *Store) GetOrCreateFolder(ctx context.Context, accountID int64, name string) (*Folder, error) {
	r, err := s.q.GetOrCreateFolder(ctx, db.GetOrCreateFolderParams{AccountID: accountID, Name: name})
	if err != nil {
		return nil, err
	}
	return &Folder{
		ID: r.ID, AccountID: accountID, Name: name,
		UIDValidity: uint32(r.Uidvalidity), //nolint:gosec // stored from uint32
		LastUID:     uint32(r.LastUid),     //nolint:gosec // stored from uint32
	}, nil
}

// ResetFolder records a new UIDVALIDITY and restarts the folder from UID 0.
func (s *Store) ResetFolder(ctx context.Context, folderID int64, uidValidity uint32) error {
	return one(s.q.ResetFolder(ctx, db.ResetFolderParams{ID: folderID, Uidvalidity: int64(uidValidity)}))
}

// MessageMeta is the parsed metadata of a message.
type MessageMeta struct {
	SHA256     string
	Size       int64
	MessageID  string
	Subject    string
	From       string
	SentAt     *time.Time
	StoredPath string
	BodyText   string // plain text for full-text search
}

// Location is where a message was found on a server.
type Location struct {
	FolderID     int64
	UIDValidity  uint32
	UID          uint32
	Flags        []string
	InternalDate time.Time
}

// MessageExists reports whether metadata for the hash is already stored.
func (s *Store) MessageExists(ctx context.Context, sha256 string) (bool, error) {
	return s.q.MessageExists(ctx, sha256)
}

// SaveBatch stores message metadata and locations for a batch and advances
// the folder's last UID, all in one transaction. It returns how many messages
// were new to the archive.
func (s *Store) SaveBatch(ctx context.Context, folderID int64, lastUID uint32, metas []MessageMeta, locs []Location) (int, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return 0, err
	}
	defer func() { _ = tx.Rollback(ctx) }()
	q := s.q.WithTx(tx)

	newCount := 0
	for i := range metas {
		m := &metas[i]
		n, err := q.InsertMessage(ctx, db.InsertMessageParams{
			Sha256: m.SHA256, Size: m.Size, MessageID: m.MessageID, Subject: m.Subject,
			FromAddr: m.From, SentAt: m.SentAt, StoredPath: m.StoredPath, BodyText: m.BodyText,
		})
		if err != nil {
			return 0, fmt.Errorf("insert message %s: %w", m.SHA256, err)
		}
		newCount += int(n)

		l := locs[i]
		flags := l.Flags
		if flags == nil {
			flags = []string{}
		}
		var internal *time.Time
		if !l.InternalDate.IsZero() {
			internal = &l.InternalDate
		}
		err = q.UpsertLocation(ctx, db.UpsertLocationParams{
			MessageSha256: m.SHA256, FolderID: l.FolderID,
			Uidvalidity: int64(l.UIDValidity), Uid: int64(l.UID),
			Flags: flags, InternalDate: internal,
		})
		if err != nil {
			return 0, fmt.Errorf("insert location: %w", err)
		}
	}
	if err := q.AdvanceFolder(ctx, db.AdvanceFolderParams{ID: folderID, LastUid: int64(lastUID)}); err != nil {
		return 0, err
	}
	return newCount, tx.Commit(ctx)
}

// TouchFolder marks a folder as synced without new messages.
func (s *Store) TouchFolder(ctx context.Context, folderID int64) error {
	return one(s.q.TouchFolder(ctx, folderID))
}

// SyncRun records the outcome of syncing one account.
type SyncRun struct {
	ID              int64
	AccountID       int64
	Status          string
	MessagesFetched int
	MessagesNew     int
	Error           string
}

// StartSyncRun creates a running sync record. Call it while holding the
// account's sync lock: it closes runs left open by a process that died.
func (s *Store) StartSyncRun(ctx context.Context, accountID int64) (*SyncRun, error) {
	if _, err := s.q.FailStaleSyncRuns(ctx, accountID); err != nil {
		return nil, err
	}
	id, err := s.q.StartSyncRun(ctx, accountID)
	if err != nil {
		return nil, err
	}
	return &SyncRun{ID: id, AccountID: accountID, Status: "running"}, nil
}

// FinishSyncRun stores the final state of a sync run.
func (s *Store) FinishSyncRun(ctx context.Context, r *SyncRun) error {
	return one(s.q.FinishSyncRun(ctx, db.FinishSyncRunParams{
		ID: r.ID, Status: r.Status, Error: r.Error,
		MessagesFetched: clampInt32(r.MessagesFetched),
		MessagesNew:     clampInt32(r.MessagesNew),
	}))
}

// UpdateSyncRunProgress stores the counters of a running sync.
func (s *Store) UpdateSyncRunProgress(ctx context.Context, r *SyncRun) error {
	return s.q.UpdateSyncRunProgress(ctx, db.UpdateSyncRunProgressParams{
		ID: r.ID, MessagesFetched: clampInt32(r.MessagesFetched), MessagesNew: clampInt32(r.MessagesNew),
	})
}

// LastRun is the most recent sync run of an account.
type LastRun struct {
	StartedAt       time.Time
	FinishedAt      *time.Time
	Status          string
	MessagesFetched int
	MessagesNew     int
	Error           string
}

// LastRuns returns the most recent sync run per account ID.
func (s *Store) LastRuns(ctx context.Context) (map[int64]LastRun, error) {
	rows, err := s.q.LastSyncRuns(ctx)
	if err != nil {
		return nil, err
	}
	out := make(map[int64]LastRun, len(rows))
	for _, r := range rows {
		out[r.AccountID] = LastRun{
			StartedAt: r.StartedAt, FinishedAt: r.FinishedAt, Status: r.Status,
			MessagesFetched: int(r.MessagesFetched), MessagesNew: int(r.MessagesNew), Error: deref(r.Error),
		}
	}
	return out, nil
}

// AccountStats summarizes the archive for one account.
type AccountStats struct {
	Account      string
	Enabled      bool
	Folders      int
	Locations    int64
	LastRunAt    *time.Time
	LastStatus   *string
	LastRunError *string
}

// Stats returns per-account statistics and the number of unique messages.
func (s *Store) Stats(ctx context.Context) ([]AccountStats, int64, error) {
	rows, err := s.q.AccountStats(ctx)
	if err != nil {
		return nil, 0, err
	}
	lastRun, err := s.LastRuns(ctx)
	if err != nil {
		return nil, 0, err
	}
	out := make([]AccountStats, 0, len(rows))
	for _, r := range rows {
		st := AccountStats{Account: r.Name, Enabled: r.Enabled, Folders: int(r.Folders), Locations: r.Locations}
		if run, ok := lastRun[r.ID]; ok {
			st.LastRunAt, st.LastStatus = &run.StartedAt, &run.Status
			if run.Error != "" {
				st.LastRunError = &run.Error
			}
		}
		out = append(out, st)
	}
	unique, err := s.q.CountMessages(ctx)
	return out, unique, err
}

// GetMessage returns the metadata of one archived message.
func (s *Store) GetMessage(ctx context.Context, sha256 string) (*MessageMeta, error) {
	r, err := s.q.GetMessage(ctx, sha256)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return &MessageMeta{
		SHA256: r.Sha256, Size: r.Size, MessageID: deref(r.MessageID), Subject: deref(r.Subject),
		From: deref(r.FromAddr), SentAt: r.SentAt, StoredPath: r.StoredPath,
	}, nil
}

// one turns the result of an :execrows query that targets a single row
// into ErrNotFound when no row matched.
func one(rows int64, err error) error {
	if err != nil {
		return err
	}
	if rows == 0 {
		return ErrNotFound
	}
	return nil
}

func clampInt32(n int) int32 {
	return int32(min(n, math.MaxInt32)) //nolint:gosec // clamped
}

func deref(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}
