// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
	"time"
)

const countAccountLocations = `-- name: CountAccountLocations :one
SELECT count(*) FROM message_locations l
JOIN folders f ON f.id = l.folder_id
WHERE f.account_id = $1
`

func (q *Queries) CountAccountLocations(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountLocations, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, host, port, tls_mode, username, password_enc, included_folders, excluded_folders, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at
`

type CreateAccountParams struct {
	Name            string
	Host            string
	Port            int32
	TlsMode         string
	Username        string
	PasswordEnc     []byte
	IncludedFolders []string
	ExcludedFolders []string
	Enabled         bool
}

type CreateAccountRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.TlsMode,
		arg.Username,
		arg.PasswordEnc,
		arg.IncludedFolders,
		arg.ExcludedFolders,
		arg.Enabled,
	)
	var i CreateAccountRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAccountFolders = `-- name: DeleteAccountFolders :exec
DELETE FROM folders WHERE account_id = $1
`

func (q *Queries) DeleteAccountFolders(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, deleteAccountFolders, accountID)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, host, port, tls_mode, username, password_enc, included_folders, excluded_folders, enabled, created_at, updated_at, removed_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.TlsMode,
		&i.Username,
		&i.PasswordEnc,
		&i.IncludedFolders,
		&i.ExcludedFolders,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const getAccountByName = `-- name: GetAccountByName :one
SELECT id, name, host, port, tls_mode, username, password_enc, included_folders, excluded_folders, enabled, created_at, updated_at, removed_at FROM accounts WHERE name = $1
`

func (q *Queries) GetAccountByName(ctx context.Context, name string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByName, name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.TlsMode,
		&i.Username,
		&i.PasswordEnc,
		&i.IncludedFolders,
		&i.ExcludedFolders,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, host, port, tls_mode, username, password_enc, included_folders, excluded_folders, enabled, created_at, updated_at, removed_at FROM accounts ORDER BY name
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.TlsMode,
			&i.Username,
			&i.PasswordEnc,
			&i.IncludedFolders,
			&i.ExcludedFolders,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAccount = `-- name: RemoveAccount :execrows
UPDATE accounts
SET removed_at = now(), enabled = FALSE, password_enc = ''::bytea, updated_at = now()
WHERE id = $1 AND removed_at IS NULL
`

// Keeps the archived data; wipes the credentials.
func (q *Queries) RemoveAccount(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, removeAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameAccount = `-- name: RenameAccount :execrows
UPDATE accounts SET name = $2, password_enc = $3, updated_at = now()
WHERE id = $1 AND removed_at IS NULL
`

type RenameAccountParams struct {
	ID          int64
	Name        string
	PasswordEnc []byte
}

// The password is encrypted with the account name as context, so it changes too.
func (q *Queries) RenameAccount(ctx context.Context, arg RenameAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameAccount, arg.ID, arg.Name, arg.PasswordEnc)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountEnabled = `-- name: SetAccountEnabled :execrows
UPDATE accounts SET enabled = $2, updated_at = now() WHERE id = $1 AND removed_at IS NULL
`

type SetAccountEnabledParams struct {
	ID      int64
	Enabled bool
}

func (q *Queries) SetAccountEnabled(ctx context.Context, arg SetAccountEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountEnabled, arg.ID, arg.Enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setFolderFilters = `-- name: SetFolderFilters :execrows
UPDATE accounts SET included_folders = $2, excluded_folders = $3, updated_at = now() WHERE id = $1 AND removed_at IS NULL
`

type SetFolderFiltersParams struct {
	ID              int64
	IncludedFolders []string
	ExcludedFolders []string
}

func (q *Queries) SetFolderFilters(ctx context.Context, arg SetFolderFiltersParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFolderFilters, arg.ID, arg.IncludedFolders, arg.ExcludedFolders)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAccountConnection = `-- name: UpdateAccountConnection :execrows
UPDATE accounts
SET host = $2, port = $3, tls_mode = $4, username = $5, password_enc = $6, updated_at = now()
WHERE id = $1 AND removed_at IS NULL
`

type UpdateAccountConnectionParams struct {
	ID          int64
	Host        string
	Port        int32
	TlsMode     string
	Username    string
	PasswordEnc []byte
}

func (q *Queries) UpdateAccountConnection(ctx context.Context, arg UpdateAccountConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAccountConnection,
		arg.ID,
		arg.Host,
		arg.Port,
		arg.TlsMode,
		arg.Username,
		arg.PasswordEnc,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePassword = `-- name: UpdatePassword :execrows
UPDATE accounts SET password_enc = $2, updated_at = now() WHERE id = $1 AND removed_at IS NULL
`

type UpdatePasswordParams struct {
	ID          int64
	PasswordEnc []byte
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordEnc)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
