// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
	"time"
)

const adoptUnownedAccounts = `-- name: AdoptUnownedAccounts :execrows
UPDATE accounts SET owner_id = $1, version = version + 1, updated_at = now() WHERE owner_id IS NULL
`

func (q *Queries) AdoptUnownedAccounts(ctx context.Context, ownerID *int64) (int64, error) {
	result, err := q.db.Exec(ctx, adoptUnownedAccounts, ownerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAccountLocations = `-- name: CountAccountLocations :one
SELECT count(*) FROM message_locations l
JOIN folders f ON f.id = l.folder_id
WHERE f.account_id = $1
`

func (q *Queries) CountAccountLocations(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountLocations, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwnedAccounts = `-- name: CountOwnedAccounts :many
SELECT owner_id, count(*) AS accounts FROM accounts WHERE owner_id IS NOT NULL GROUP BY owner_id
`

type CountOwnedAccountsRow struct {
	OwnerID  *int64
	Accounts int64
}

func (q *Queries) CountOwnedAccounts(ctx context.Context) ([]CountOwnedAccountsRow, error) {
	rows, err := q.db.Query(ctx, countOwnedAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOwnedAccountsRow
	for rows.Next() {
		var i CountOwnedAccountsRow
		if err := rows.Scan(&i.OwnerID, &i.Accounts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, host, port, tls_mode, username, password_enc, included_folders, excluded_folders, enabled, owner_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, created_at, version
`

type CreateAccountParams struct {
	Name            string
	Host            string
	Port            int32
	TlsMode         string
	Username        string
	PasswordEnc     []byte
	IncludedFolders []string
	ExcludedFolders []string
	Enabled         bool
	OwnerID         *int64
}

type CreateAccountRow struct {
	ID        int64
	CreatedAt time.Time
	Version   int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.TlsMode,
		arg.Username,
		arg.PasswordEnc,
		arg.IncludedFolders,
		arg.ExcludedFolders,
		arg.Enabled,
		arg.OwnerID,
	)
	var i CreateAccountRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Version)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAccountFolders = `-- name: DeleteAccountFolders :exec
DELETE FROM folders WHERE account_id = $1
`

func (q *Queries) DeleteAccountFolders(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, deleteAccountFolders, accountID)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, host, port, tls_mode, username, password_enc, included_folders, excluded_folders, enabled, created_at, updated_at, removed_at, owner_id, version FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.TlsMode,
		&i.Username,
		&i.PasswordEnc,
		&i.IncludedFolders,
		&i.ExcludedFolders,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
		&i.OwnerID,
		&i.Version,
	)
	return i, err
}

const getOwnedAccount = `-- name: GetOwnedAccount :one
SELECT id, name, host, port, tls_mode, username, password_enc, included_folders, excluded_folders, enabled, created_at, updated_at, removed_at, owner_id, version FROM accounts WHERE owner_id = $1 AND name = $2
`

type GetOwnedAccountParams struct {
	OwnerID *int64
	Name    string
}

func (q *Queries) GetOwnedAccount(ctx context.Context, arg GetOwnedAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getOwnedAccount, arg.OwnerID, arg.Name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.TlsMode,
		&i.Username,
		&i.PasswordEnc,
		&i.IncludedFolders,
		&i.ExcludedFolders,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
		&i.OwnerID,
		&i.Version,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, host, port, tls_mode, username, password_enc, included_folders, excluded_folders, enabled, created_at, updated_at, removed_at, owner_id, version FROM accounts ORDER BY name
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.TlsMode,
			&i.Username,
			&i.PasswordEnc,
			&i.IncludedFolders,
			&i.ExcludedFolders,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RemovedAt,
			&i.OwnerID,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByName = `-- name: ListAccountsByName :many
SELECT id, name, host, port, tls_mode, username, password_enc, included_folders, excluded_folders, enabled, created_at, updated_at, removed_at, owner_id, version FROM accounts WHERE name = $1 ORDER BY owner_id NULLS FIRST
`

// Accounts of all users with this name, for the CLI.
func (q *Queries) ListAccountsByName(ctx context.Context, name string) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.TlsMode,
			&i.Username,
			&i.PasswordEnc,
			&i.IncludedFolders,
			&i.ExcludedFolders,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RemovedAt,
			&i.OwnerID,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedAccounts = `-- name: ListOwnedAccounts :many
SELECT id, name, host, port, tls_mode, username, password_enc, included_folders, excluded_folders, enabled, created_at, updated_at, removed_at, owner_id, version FROM accounts WHERE owner_id = $1 ORDER BY name
`

func (q *Queries) ListOwnedAccounts(ctx context.Context, ownerID *int64) ([]Account, error) {
	rows, err := q.db.Query(ctx, listOwnedAccounts, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.TlsMode,
			&i.Username,
			&i.PasswordEnc,
			&i.IncludedFolders,
			&i.ExcludedFolders,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RemovedAt,
			&i.OwnerID,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccount = `-- name: LockAccount :one
SELECT id, name, host, port, tls_mode, username, password_enc, included_folders, excluded_folders, enabled, created_at, updated_at, removed_at, owner_id, version FROM accounts WHERE id = $1 FOR UPDATE
`

// The row stays locked until the transaction ends.
func (q *Queries) LockAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, lockAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.TlsMode,
		&i.Username,
		&i.PasswordEnc,
		&i.IncludedFolders,
		&i.ExcludedFolders,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
		&i.OwnerID,
		&i.Version,
	)
	return i, err
}

const removeAccount = `-- name: RemoveAccount :execrows
UPDATE accounts
SET removed_at = now(), enabled = FALSE, password_enc = ''::bytea, version = version + 1, updated_at = now()
WHERE id = $1 AND removed_at IS NULL
`

// Keeps the archived data; wipes the credentials.
func (q *Queries) RemoveAccount(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, removeAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replacePassword = `-- name: ReplacePassword :execrows
UPDATE accounts SET password_enc = $1 WHERE id = $2 AND password_enc = $3
`

type ReplacePasswordParams struct {
	NewEnc []byte
	ID     int64
	OldEnc []byte
}

// Compare-and-swap: only if the password is still the one that was read.
// The logical state does not change, so the version stays.
func (q *Queries) ReplacePassword(ctx context.Context, arg ReplacePasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, replacePassword, arg.NewEnc, arg.ID, arg.OldEnc)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountOwner = `-- name: SetAccountOwner :execrows
UPDATE accounts SET owner_id = $2, version = version + 1, updated_at = now() WHERE id = $1
`

type SetAccountOwnerParams struct {
	ID      int64
	OwnerID *int64
}

func (q *Queries) SetAccountOwner(ctx context.Context, arg SetAccountOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountOwner, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePassword = `-- name: UpdatePassword :execrows
UPDATE accounts SET password_enc = $2 WHERE id = $1
`

type UpdatePasswordParams struct {
	ID          int64
	PasswordEnc []byte
}

// Only for a new account, inside the transaction that creates it.
func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordEnc)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userOwnsAccounts = `-- name: UserOwnsAccounts :one
SELECT EXISTS (SELECT 1 FROM accounts WHERE owner_id = $1)
`

func (q *Queries) UserOwnsAccounts(ctx context.Context, ownerID *int64) (bool, error) {
	row := q.db.QueryRow(ctx, userOwnsAccounts, ownerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const writeAccount = `-- name: WriteAccount :exec
UPDATE accounts
SET name = $1, host = $2, port = $3, tls_mode = $4, username = $5,
    password_enc = $6, included_folders = $7,
    excluded_folders = $8, enabled = $9,
    version = version + 1, updated_at = now()
WHERE id = $10
`

type WriteAccountParams struct {
	Name            string
	Host            string
	Port            int32
	TlsMode         string
	Username        string
	PasswordEnc     []byte
	IncludedFolders []string
	ExcludedFolders []string
	Enabled         bool
	ID              int64
}

func (q *Queries) WriteAccount(ctx context.Context, arg WriteAccountParams) error {
	_, err := q.db.Exec(ctx, writeAccount,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.TlsMode,
		arg.Username,
		arg.PasswordEnc,
		arg.IncludedFolders,
		arg.ExcludedFolders,
		arg.Enabled,
		arg.ID,
	)
	return err
}
