// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"
	"time"
)

const countConversation = `-- name: CountConversation :one
WITH me AS (
    SELECT x.sha256, x.message_id, x.in_reply_to, COALESCE(x.thread_id, x.sha256)::text AS thread_key
    FROM messages x WHERE x.sha256 = $2
)
SELECT count(*)::bigint
FROM messages m, me
WHERE (COALESCE(m.thread_id, m.sha256) = me.thread_key
       OR m.message_id = me.in_reply_to
       OR m.in_reply_to = me.message_id
       OR m.reference_ids @> ARRAY[me.message_id])
  AND EXISTS (
      SELECT 1 FROM message_locations l
      JOIN folders f ON f.id = l.folder_id
      JOIN accounts a ON a.id = f.account_id
      WHERE l.message_sha256 = m.sha256 AND a.owner_id = $1::bigint)
`

type CountConversationParams struct {
	Owner  int64
	Sha256 string
}

func (q *Queries) CountConversation(ctx context.Context, arg CountConversationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConversation, arg.Owner, arg.Sha256)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listConversation = `-- name: ListConversation :many

WITH me AS (
    SELECT x.sha256, x.message_id, x.in_reply_to, COALESCE(x.thread_id, x.sha256)::text AS thread_key
    FROM messages x WHERE x.sha256 = $3
)
SELECT m.sha256, m.subject, m.from_addr, m.sent_at, m.sort_at,
       (CASE
            WHEN m.sha256 = me.sha256 THEN 'self'
            WHEN m.message_id = me.in_reply_to THEN 'parent'
            WHEN m.in_reply_to = me.message_id OR m.reference_ids @> ARRAY[me.message_id] THEN 'reply'
            ELSE 'thread'
        END)::text AS relation
FROM messages m, me
WHERE (COALESCE(m.thread_id, m.sha256) = me.thread_key
       OR m.message_id = me.in_reply_to
       OR m.in_reply_to = me.message_id
       OR m.reference_ids @> ARRAY[me.message_id])
  AND EXISTS (
      SELECT 1 FROM message_locations l
      JOIN folders f ON f.id = l.folder_id
      JOIN accounts a ON a.id = f.account_id
      WHERE l.message_sha256 = m.sha256 AND a.owner_id = $1::bigint)
ORDER BY m.sort_at DESC, m.sha256 DESC
LIMIT $2
`

type ListConversationParams struct {
	Owner    int64
	RowLimit int32
	Sha256   string
}

type ListConversationRow struct {
	Sha256   string
	Subject  *string
	FromAddr *string
	SentAt   *time.Time
	SortAt   *time.Time
	Relation string
}

// The conversation of a message: the other messages of its thread, plus one
// hop of direct links that need no common thread ID: the parent (its
// Message-ID is the message's In-Reply-To) and the replies (their
// In-Reply-To or References name the message's Message-ID). Only messages
// found in one of the user's accounts.
// The newest row_limit members, newest first; the caller reverses them.
func (q *Queries) ListConversation(ctx context.Context, arg ListConversationParams) ([]ListConversationRow, error) {
	rows, err := q.db.Query(ctx, listConversation, arg.Owner, arg.RowLimit, arg.Sha256)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationRow
	for rows.Next() {
		var i ListConversationRow
		if err := rows.Scan(
			&i.Sha256,
			&i.Subject,
			&i.FromAddr,
			&i.SentAt,
			&i.SortAt,
			&i.Relation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
