// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package db

import (
	"context"
	"time"
)

const advanceFolder = `-- name: AdvanceFolder :exec
UPDATE folders SET last_uid = GREATEST(last_uid, $1::bigint), last_synced_at = now() WHERE id = $2
`

type AdvanceFolderParams struct {
	LastUid int64
	ID      int64
}

func (q *Queries) AdvanceFolder(ctx context.Context, arg AdvanceFolderParams) error {
	_, err := q.db.Exec(ctx, advanceFolder, arg.LastUid, arg.ID)
	return err
}

const getOrCreateFolder = `-- name: GetOrCreateFolder :one
INSERT INTO folders (account_id, name) VALUES ($1, $2)
ON CONFLICT (account_id, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, uidvalidity, last_uid, last_reconciled_at
`

type GetOrCreateFolderParams struct {
	AccountID int64
	Name      string
}

type GetOrCreateFolderRow struct {
	ID               int64
	Uidvalidity      int64
	LastUid          int64
	LastReconciledAt *time.Time
}

func (q *Queries) GetOrCreateFolder(ctx context.Context, arg GetOrCreateFolderParams) (GetOrCreateFolderRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateFolder, arg.AccountID, arg.Name)
	var i GetOrCreateFolderRow
	err := row.Scan(
		&i.ID,
		&i.Uidvalidity,
		&i.LastUid,
		&i.LastReconciledAt,
	)
	return i, err
}

const locationInFolder = `-- name: LocationInFolder :one
SELECT EXISTS (SELECT 1 FROM message_locations WHERE message_sha256 = $1 AND folder_id = $2)
`

type LocationInFolderParams struct {
	Sha256   string
	FolderID int64
}

// Whether the message already has a location in the folder; uses
// message_locations_sha_idx.
func (q *Queries) LocationInFolder(ctx context.Context, arg LocationInFolderParams) (bool, error) {
	row := q.db.QueryRow(ctx, locationInFolder, arg.Sha256, arg.FolderID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const resetFolder = `-- name: ResetFolder :execrows
UPDATE folders SET uidvalidity = $2, last_uid = 0 WHERE id = $1
`

type ResetFolderParams struct {
	ID          int64
	Uidvalidity int64
}

func (q *Queries) ResetFolder(ctx context.Context, arg ResetFolderParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetFolder, arg.ID, arg.Uidvalidity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchFolder = `-- name: TouchFolder :execrows
UPDATE folders SET last_synced_at = now() WHERE id = $1
`

func (q *Queries) TouchFolder(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, touchFolder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
