// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loss_alerts.sql

package db

import (
	"context"
	"time"
)

const claimLossAlerts = `-- name: ClaimLossAlerts :many
UPDATE loss_alerts la
SET notify_lease = $1, notify_lease_until = now() + make_interval(secs => $2::float8)
FROM accounts a LEFT JOIN users u ON u.id = a.owner_id
WHERE la.account_id = a.id AND la.id IN (
    SELECT c.id FROM loss_alerts c JOIN accounts ca ON ca.id = c.account_id
    WHERE c.sent_at IS NULL AND c.given_up_at IS NULL AND ca.removed_at IS NULL
      AND c.created_at > now() - make_interval(secs => $3::float8)
      AND (c.notify_next_at IS NULL OR c.notify_next_at <= now())
      AND (c.notify_lease_until IS NULL OR c.notify_lease_until < now())
    ORDER BY c.id
    LIMIT $4
    FOR UPDATE OF c SKIP LOCKED)
RETURNING la.id, la.sync_run_id, la.account_id, a.name AS account_name, coalesce(u.name, '')::text AS owner_name,
    la.created_at, la.lost, la.present_before, la.folder_names, la.folder_lost, la.more_folders, la.notify_attempts
`

type ClaimLossAlertsParams struct {
	Lease         []byte
	LeaseSeconds  float64
	MaxAgeSeconds float64
	MaxRows       int32
}

type ClaimLossAlertsRow struct {
	ID             int64
	SyncRunID      int64
	AccountID      int64
	AccountName    string
	OwnerName      string
	CreatedAt      time.Time
	Lost           int32
	PresentBefore  int32
	FolderNames    []string
	FolderLost     []int32
	MoreFolders    int32
	NotifyAttempts int32
}

// Leases up to max_rows unsent alerts that are due and younger than
// max_age, of accounts that were not removed. Rows another notifier holds
// are skipped.
func (q *Queries) ClaimLossAlerts(ctx context.Context, arg ClaimLossAlertsParams) ([]ClaimLossAlertsRow, error) {
	rows, err := q.db.Query(ctx, claimLossAlerts,
		arg.Lease,
		arg.LeaseSeconds,
		arg.MaxAgeSeconds,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimLossAlertsRow
	for rows.Next() {
		var i ClaimLossAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.SyncRunID,
			&i.AccountID,
			&i.AccountName,
			&i.OwnerName,
			&i.CreatedAt,
			&i.Lost,
			&i.PresentBefore,
			&i.FolderNames,
			&i.FolderLost,
			&i.MoreFolders,
			&i.NotifyAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPresentMessages = `-- name: CountPresentMessages :one
SELECT count(DISTINCT l.message_sha256)::bigint FROM message_locations l
JOIN folders f ON f.id = l.folder_id
WHERE f.account_id = $1 AND l.gone_at IS NULL
`

// Distinct messages of the account that are still on the server.
func (q *Queries) CountPresentMessages(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPresentMessages, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deferLossAlert = `-- name: DeferLossAlert :execrows
UPDATE loss_alerts
SET notify_attempts = notify_attempts + 1, notify_next_at = $1::timestamptz, notify_error = $2::text,
    notify_lease = NULL, notify_lease_until = NULL
WHERE id = $3 AND notify_lease = $4
`

type DeferLossAlertParams struct {
	NextAt      time.Time
	NotifyError string
	ID          int64
	Lease       []byte
}

func (q *Queries) DeferLossAlert(ctx context.Context, arg DeferLossAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, deferLossAlert,
		arg.NextAt,
		arg.NotifyError,
		arg.ID,
		arg.Lease,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireLossAlerts = `-- name: ExpireLossAlerts :execrows
UPDATE loss_alerts
SET given_up_at = now(), notify_error = coalesce(notify_error, 'not sent in time'),
    notify_lease = NULL, notify_lease_until = NULL
WHERE sent_at IS NULL AND given_up_at IS NULL
  AND created_at < now() - make_interval(secs => $1::float8)
  AND (notify_lease_until IS NULL OR notify_lease_until < now())
`

// Alerts that were not sent within max_age are given up, so that a webhook
// configured later never sends old losses and the pending index stays small.
func (q *Queries) ExpireLossAlerts(ctx context.Context, maxAgeSeconds float64) (int64, error) {
	result, err := q.db.Exec(ctx, expireLossAlerts, maxAgeSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishLossAlert = `-- name: FinishLossAlert :execrows
UPDATE loss_alerts
SET sent_at = CASE WHEN $1::boolean THEN NULL ELSE now() END,
    given_up_at = CASE WHEN $1::boolean THEN now() END,
    notify_error = NULLIF($2::text, ''),
    notify_lease = NULL, notify_lease_until = NULL
WHERE id = $3 AND notify_lease = $4
`

type FinishLossAlertParams struct {
	GivenUp     bool
	NotifyError string
	ID          int64
	Lease       []byte
}

// Sent, or given up with an error. Only the notifier holding the lease may
// do this.
func (q *Queries) FinishLossAlert(ctx context.Context, arg FinishLossAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishLossAlert,
		arg.GivenUp,
		arg.NotifyError,
		arg.ID,
		arg.Lease,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertLossAlert = `-- name: InsertLossAlert :exec
INSERT INTO loss_alerts (account_id, sync_run_id, lost, present_before, folder_names, folder_lost, more_folders)
VALUES ($1, $2, $3, $4, $5::text[], $6::int[], $7)
`

type InsertLossAlertParams struct {
	AccountID     int64
	SyncRunID     int64
	Lost          int32
	PresentBefore int32
	FolderNames   []string
	FolderLost    []int32
	MoreFolders   int32
}

func (q *Queries) InsertLossAlert(ctx context.Context, arg InsertLossAlertParams) error {
	_, err := q.db.Exec(ctx, insertLossAlert,
		arg.AccountID,
		arg.SyncRunID,
		arg.Lost,
		arg.PresentBefore,
		arg.FolderNames,
		arg.FolderLost,
		arg.MoreFolders,
	)
	return err
}

const lostMessages = `-- name: LostMessages :many

WITH lost AS (
    SELECT l.message_sha256, f.name AS folder
    FROM message_locations l
    JOIN folders f ON f.id = l.folder_id
    WHERE f.account_id = $1 AND l.gone_at IS NOT NULL
      AND l.gone_at >= (SELECT r.started_at FROM sync_runs r WHERE r.id = $2)
      AND NOT (l.folder_id = ANY ($3::bigint[]))
      AND NOT EXISTS (
          SELECT 1 FROM message_locations p JOIN folders pf ON pf.id = p.folder_id
          WHERE p.message_sha256 = l.message_sha256 AND pf.account_id = $1 AND p.gone_at IS NULL)
)
SELECT coalesce(folder, '')::text AS folder, (GROUPING(folder) = 1)::boolean AS total,
       count(DISTINCT message_sha256)::bigint AS lost
FROM lost
GROUP BY ROLLUP (folder)
ORDER BY GROUPING(folder), lost DESC, folder
`

type LostMessagesParams struct {
	AccountID int64
	RunID     int64
	Baseline  []int64
}

type LostMessagesRow struct {
	Folder string
	Total  bool
	Lost   int64
}

// Alerts about messages deleted on the server in bulk (see 00016).
// Messages of the account that lost their last present location in the
// run: a location of theirs went gone during the run, outside the folders
// whose first reconcile ran in it (those only catch up with old
// deletions), and none of their locations in the account is present. Gone
// locations are read from message_locations_gone_idx. One row per folder
// where such a location went gone, and a last row marked total with the
// number of distinct messages.
func (q *Queries) LostMessages(ctx context.Context, arg LostMessagesParams) ([]LostMessagesRow, error) {
	rows, err := q.db.Query(ctx, lostMessages, arg.AccountID, arg.RunID, arg.Baseline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LostMessagesRow
	for rows.Next() {
		var i LostMessagesRow
		if err := rows.Scan(&i.Folder, &i.Total, &i.Lost); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
