// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package db

import (
	"context"
	"time"
)

const existingMessages = `-- name: ExistingMessages :many
SELECT sha256::text FROM messages WHERE sha256 = ANY($1::text[])
`

// The hashes of the list that have a messages row.
func (q *Queries) ExistingMessages(ctx context.Context, hashes []string) ([]string, error) {
	rows, err := q.db.Query(ctx, existingMessages, hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sha256 string
		if err := rows.Scan(&sha256); err != nil {
			return nil, err
		}
		items = append(items, sha256)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportFolders = `-- name: ListExportFolders :many
SELECT f.id, a.name AS account, f.name AS folder
FROM folders f
JOIN accounts a ON a.id = f.account_id
WHERE a.id = ANY($1::bigint[])
  AND a.owner_id IS NOT DISTINCT FROM $2::bigint
  AND ($3::text = '' OR f.name = $3::text)
ORDER BY a.name, f.name, f.id
`

type ListExportFoldersParams struct {
	AccountIds []int64
	Owner      *int64
	Folder     string
}

type ListExportFoldersRow struct {
	ID      int64
	Account string
	Folder  string
}

// The folders of the given accounts, only if they belong to owner (NULL for
// accounts without owner). An empty folder name means all folders.
func (q *Queries) ListExportFolders(ctx context.Context, arg ListExportFoldersParams) ([]ListExportFoldersRow, error) {
	rows, err := q.db.Query(ctx, listExportFolders, arg.AccountIds, arg.Owner, arg.Folder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportFoldersRow
	for rows.Next() {
		var i ListExportFoldersRow
		if err := rows.Scan(&i.ID, &i.Account, &i.Folder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportLocations = `-- name: ListExportLocations :many
SELECT l.message_sha256::text AS sha256, l.uidvalidity, l.uid, l.flags, l.internal_date,
       m.sent_at, m.size
FROM message_locations l
JOIN messages m ON m.sha256 = l.message_sha256
JOIN folders f ON f.id = l.folder_id
JOIN accounts a ON a.id = f.account_id
WHERE l.folder_id = $1
  AND a.owner_id IS NOT DISTINCT FROM $2::bigint
  AND l.id <= $3::bigint
  AND (l.uidvalidity, l.uid) > ($4::bigint, $5::bigint)
ORDER BY l.uidvalidity, l.uid
LIMIT $6
`

type ListExportLocationsParams struct {
	FolderID         int64
	Owner            *int64
	MaxID            int64
	AfterUidvalidity int64
	AfterUid         int64
	PageSize         int32
}

type ListExportLocationsRow struct {
	Sha256       string
	Uidvalidity  int64
	Uid          int64
	Flags        []string
	InternalDate *time.Time
	SentAt       *time.Time
	Size         int64
}

// One page of a folder's locations up to max_id, by (uidvalidity, uid), with
// the same owner check as ListExportFolders.
func (q *Queries) ListExportLocations(ctx context.Context, arg ListExportLocationsParams) ([]ListExportLocationsRow, error) {
	rows, err := q.db.Query(ctx, listExportLocations,
		arg.FolderID,
		arg.Owner,
		arg.MaxID,
		arg.AfterUidvalidity,
		arg.AfterUid,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportLocationsRow
	for rows.Next() {
		var i ListExportLocationsRow
		if err := rows.Scan(
			&i.Sha256,
			&i.Uidvalidity,
			&i.Uid,
			&i.Flags,
			&i.InternalDate,
			&i.SentAt,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT sha256, size, stored_path FROM messages
WHERE sha256 > $1::text
ORDER BY sha256
LIMIT $2
`

type ListMessagesAfterParams struct {
	After    string
	PageSize int32
}

type ListMessagesAfterRow struct {
	Sha256     string
	Size       int64
	StoredPath string
}

// One page of all messages by hash, for verify.
func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]ListMessagesAfterRow, error) {
	rows, err := q.db.Query(ctx, listMessagesAfter, arg.After, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesAfterRow
	for rows.Next() {
		var i ListMessagesAfterRow
		if err := rows.Scan(&i.Sha256, &i.Size, &i.StoredPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationsOfMessages = `-- name: LocationsOfMessages :many
SELECT l.message_sha256::text AS sha256, coalesce(u.name, '') AS owner, a.name AS account,
       f.name AS folder, l.uidvalidity, l.uid
FROM message_locations l
JOIN folders f ON f.id = l.folder_id
JOIN accounts a ON a.id = f.account_id
LEFT JOIN users u ON u.id = a.owner_id
WHERE l.message_sha256 = ANY($1::text[])
ORDER BY l.message_sha256, u.name, a.name, f.name, l.uidvalidity, l.uid
`

type LocationsOfMessagesRow struct {
	Sha256      string
	Owner       string
	Account     string
	Folder      string
	Uidvalidity int64
	Uid         int64
}

// Where messages were found, to tell owners what to restore.
func (q *Queries) LocationsOfMessages(ctx context.Context, hashes []string) ([]LocationsOfMessagesRow, error) {
	rows, err := q.db.Query(ctx, locationsOfMessages, hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocationsOfMessagesRow
	for rows.Next() {
		var i LocationsOfMessagesRow
		if err := rows.Scan(
			&i.Sha256,
			&i.Owner,
			&i.Account,
			&i.Folder,
			&i.Uidvalidity,
			&i.Uid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxLocationID = `-- name: MaxLocationID :one
SELECT coalesce(max(id), 0)::bigint FROM message_locations
`

func (q *Queries) MaxLocationID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, maxLocationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
