// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"time"
)

const countMessages = `-- name: CountMessages :one
SELECT count(*) FROM messages
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwnedMessages = `-- name: CountOwnedMessages :one
SELECT count(DISTINCT l.message_sha256) FROM message_locations l
JOIN folders f ON f.id = l.folder_id
JOIN accounts a ON a.id = f.account_id
WHERE a.owner_id = $1
`

// Unique messages found in the user's accounts.
func (q *Queries) CountOwnedMessages(ctx context.Context, ownerID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnedMessages, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMessage = `-- name: GetMessage :one
SELECT sha256, size, message_id, subject, from_addr, sent_at, stored_path
FROM messages WHERE sha256 = $1
`

type GetMessageRow struct {
	Sha256     string
	Size       int64
	MessageID  *string
	Subject    *string
	FromAddr   *string
	SentAt     *time.Time
	StoredPath string
}

func (q *Queries) GetMessage(ctx context.Context, sha256 string) (GetMessageRow, error) {
	row := q.db.QueryRow(ctx, getMessage, sha256)
	var i GetMessageRow
	err := row.Scan(
		&i.Sha256,
		&i.Size,
		&i.MessageID,
		&i.Subject,
		&i.FromAddr,
		&i.SentAt,
		&i.StoredPath,
	)
	return i, err
}

const hasUnindexed = `-- name: HasUnindexed :one
SELECT EXISTS (SELECT 1 FROM messages WHERE index_version < $1)
`

func (q *Queries) HasUnindexed(ctx context.Context, indexVersion int16) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnindexed, indexVersion)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertMessage = `-- name: InsertMessage :execrows
INSERT INTO messages (sha256, size, message_id, subject, from_addr, sent_at, stored_path, body_text,
                      to_addr, cc_addr, attachment_names, has_attachment,
                      in_reply_to, reference_ids, thread_id, index_version)
VALUES ($1, $2, NULLIF($3::text, ''), NULLIF($4::text, ''),
        NULLIF($5::text, ''), $6, $7, $8::text,
        NULLIF($9::text, ''), NULLIF($10::text, ''), NULLIF($11::text, ''),
        $12, NULLIF($13::text, ''), $14::text[], NULLIF($15::text, ''),
        $16)
ON CONFLICT (sha256) DO NOTHING
`

type InsertMessageParams struct {
	Sha256          string
	Size            int64
	MessageID       string
	Subject         string
	FromAddr        string
	SentAt          *time.Time
	StoredPath      string
	BodyText        string
	ToAddr          string
	CcAddr          string
	AttachmentNames string
	HasAttachment   bool
	InReplyTo       string
	ReferenceIds    []string
	ThreadID        string
	IndexVersion    int16
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMessage,
		arg.Sha256,
		arg.Size,
		arg.MessageID,
		arg.Subject,
		arg.FromAddr,
		arg.SentAt,
		arg.StoredPath,
		arg.BodyText,
		arg.ToAddr,
		arg.CcAddr,
		arg.AttachmentNames,
		arg.HasAttachment,
		arg.InReplyTo,
		arg.ReferenceIds,
		arg.ThreadID,
		arg.IndexVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUnindexed = `-- name: ListUnindexed :many
SELECT sha256, stored_path FROM messages
WHERE index_version < $1 AND sha256 > $2::bpchar
ORDER BY sha256
LIMIT $3
`

type ListUnindexedParams struct {
	IndexVersion int16
	After        string
	RowLimit     int32
}

type ListUnindexedRow struct {
	Sha256     string
	StoredPath string
}

// Messages extracted by an older version, in primary key order after the
// last one seen, so a full pass reads the table once. The bpchar cast lets
// the primary key index seek to the start of each batch.
func (q *Queries) ListUnindexed(ctx context.Context, arg ListUnindexedParams) ([]ListUnindexedRow, error) {
	rows, err := q.db.Query(ctx, listUnindexed, arg.IndexVersion, arg.After, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnindexedRow
	for rows.Next() {
		var i ListUnindexedRow
		if err := rows.Scan(&i.Sha256, &i.StoredPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageExists = `-- name: MessageExists :one
SELECT EXISTS (SELECT 1 FROM messages WHERE sha256 = $1)
`

func (q *Queries) MessageExists(ctx context.Context, sha256 string) (bool, error) {
	row := q.db.QueryRow(ctx, messageExists, sha256)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setIndexData = `-- name: SetIndexData :execrows
UPDATE messages
SET body_text = $1::text, to_addr = NULLIF($2::text, ''), cc_addr = NULLIF($3::text, ''),
    attachment_names = NULLIF($4::text, ''), has_attachment = $5,
    in_reply_to = NULLIF($6::text, ''), reference_ids = $7::text[],
    thread_id = NULLIF($8::text, ''), index_version = $9
WHERE sha256 = $10 AND index_version < $9
`

type SetIndexDataParams struct {
	BodyText        string
	ToAddr          string
	CcAddr          string
	AttachmentNames string
	HasAttachment   bool
	InReplyTo       string
	ReferenceIds    []string
	ThreadID        string
	IndexVersion    int16
	Sha256          string
}

// Never overwrites a row that a newer version already extracted.
func (q *Queries) SetIndexData(ctx context.Context, arg SetIndexDataParams) (int64, error) {
	result, err := q.db.Exec(ctx, setIndexData,
		arg.BodyText,
		arg.ToAddr,
		arg.CcAddr,
		arg.AttachmentNames,
		arg.HasAttachment,
		arg.InReplyTo,
		arg.ReferenceIds,
		arg.ThreadID,
		arg.IndexVersion,
		arg.Sha256,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertLocation = `-- name: UpsertLocation :exec
INSERT INTO message_locations (message_sha256, folder_id, uidvalidity, uid, flags, internal_date)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (folder_id, uidvalidity, uid)
DO UPDATE SET flags = EXCLUDED.flags, last_seen_at = now()
`

type UpsertLocationParams struct {
	MessageSha256 string
	FolderID      int64
	Uidvalidity   int64
	Uid           int64
	Flags         []string
	InternalDate  *time.Time
}

func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) error {
	_, err := q.db.Exec(ctx, upsertLocation,
		arg.MessageSha256,
		arg.FolderID,
		arg.Uidvalidity,
		arg.Uid,
		arg.Flags,
		arg.InternalDate,
	)
	return err
}
