// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"time"
)

const countMessages = `-- name: CountMessages :one
SELECT count(*) FROM messages
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMessage = `-- name: GetMessage :one
SELECT sha256, size, message_id, subject, from_addr, sent_at, stored_path
FROM messages WHERE sha256 = $1
`

type GetMessageRow struct {
	Sha256     string
	Size       int64
	MessageID  *string
	Subject    *string
	FromAddr   *string
	SentAt     *time.Time
	StoredPath string
}

func (q *Queries) GetMessage(ctx context.Context, sha256 string) (GetMessageRow, error) {
	row := q.db.QueryRow(ctx, getMessage, sha256)
	var i GetMessageRow
	err := row.Scan(
		&i.Sha256,
		&i.Size,
		&i.MessageID,
		&i.Subject,
		&i.FromAddr,
		&i.SentAt,
		&i.StoredPath,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :execrows
INSERT INTO messages (sha256, size, message_id, subject, from_addr, sent_at, stored_path)
VALUES ($1, $2, NULLIF($3::text, ''), NULLIF($4::text, ''),
        NULLIF($5::text, ''), $6, $7)
ON CONFLICT (sha256) DO NOTHING
`

type InsertMessageParams struct {
	Sha256     string
	Size       int64
	MessageID  string
	Subject    string
	FromAddr   string
	SentAt     *time.Time
	StoredPath string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMessage,
		arg.Sha256,
		arg.Size,
		arg.MessageID,
		arg.Subject,
		arg.FromAddr,
		arg.SentAt,
		arg.StoredPath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const messageExists = `-- name: MessageExists :one
SELECT EXISTS (SELECT 1 FROM messages WHERE sha256 = $1)
`

func (q *Queries) MessageExists(ctx context.Context, sha256 string) (bool, error) {
	row := q.db.QueryRow(ctx, messageExists, sha256)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertLocation = `-- name: UpsertLocation :exec
INSERT INTO message_locations (message_sha256, folder_id, uidvalidity, uid, flags, internal_date)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (folder_id, uidvalidity, uid)
DO UPDATE SET flags = EXCLUDED.flags, last_seen_at = now()
`

type UpsertLocationParams struct {
	MessageSha256 string
	FolderID      int64
	Uidvalidity   int64
	Uid           int64
	Flags         []string
	InternalDate  *time.Time
}

func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) error {
	_, err := q.db.Exec(ctx, upsertLocation,
		arg.MessageSha256,
		arg.FolderID,
		arg.Uidvalidity,
		arg.Uid,
		arg.Flags,
		arg.InternalDate,
	)
	return err
}
