// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Account struct {
	ID              int64
	Name            string
	Host            string
	Port            int32
	TlsMode         string
	Username        string
	PasswordEnc     []byte
	IncludedFolders []string
	ExcludedFolders []string
	Enabled         bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	RemovedAt       *time.Time
	OwnerID         *int64
	Version         int64
}

type Folder struct {
	ID           int64
	AccountID    int64
	Name         string
	Uidvalidity  int64
	LastUid      int64
	LastSyncedAt *time.Time
}

type Message struct {
	Sha256     string
	Size       int64
	MessageID  *string
	Subject    *string
	FromAddr   *string
	SentAt     *time.Time
	StoredPath string
	CreatedAt  time.Time
	BodyText   *string
	SortAt     *time.Time
	Search     interface{}
}

type MessageLocation struct {
	ID            int64
	MessageSha256 string
	FolderID      int64
	Uidvalidity   int64
	Uid           int64
	Flags         []string
	InternalDate  *time.Time
	FirstSeenAt   time.Time
	LastSeenAt    time.Time
}

type Passkey struct {
	ID           int64
	UserID       int64
	CredentialID []byte
	Name         string
	Credential   []byte
	CreatedAt    time.Time
	LastUsedAt   *time.Time
}

type Session struct {
	ID         []byte
	UserID     int64
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	UserAgent  string
}

type SyncRun struct {
	ID              int64
	AccountID       int64
	StartedAt       time.Time
	FinishedAt      *time.Time
	Status          string
	MessagesFetched int32
	MessagesNew     int32
	Error           *string
}

type TwoFactorChallenge struct {
	ID               []byte
	UserID           int64
	TwoFactorVersion int64
	CreatedAt        time.Time
	ExpiresAt        time.Time
}

type TwoFactorRecoveryCode struct {
	ID       int64
	UserID   int64
	CodeHash []byte
	UsedAt   *time.Time
}

type User struct {
	ID                     int64
	Name                   string
	PasswordHash           string
	IsAdmin                bool
	LockedAt               *time.Time
	CreatedAt              time.Time
	PasswordChangedAt      time.Time
	LastLoginAt            *time.Time
	MustChangePassword     bool
	TwoFactorSecret        []byte
	TwoFactorEnabled       bool
	TwoFactorPendingSecret []byte
	TwoFactorLastCounter   *int64
	TwoFactorVersion       int64
	WebauthnHandle         []byte
}

type WebauthnCeremony struct {
	ID        []byte
	Kind      string
	UserID    *int64
	Name      *string
	Data      []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}
