// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passkeys.sql

package db

import (
	"context"
	"time"
)

const countOpenLoginCeremonies = `-- name: CountOpenLoginCeremonies :one
SELECT count(*) FROM webauthn_ceremonies WHERE kind = 'login' AND expires_at > now()
`

func (q *Queries) CountOpenLoginCeremonies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenLoginCeremonies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPasskeys = `-- name: CountPasskeys :one
SELECT count(*) FROM passkeys WHERE user_id = $1
`

func (q *Queries) CountPasskeys(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPasskeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPasskeysByUser = `-- name: CountPasskeysByUser :many
SELECT user_id, count(*) AS n FROM passkeys GROUP BY user_id
`

type CountPasskeysByUserRow struct {
	UserID int64
	N      int64
}

func (q *Queries) CountPasskeysByUser(ctx context.Context) ([]CountPasskeysByUserRow, error) {
	rows, err := q.db.Query(ctx, countPasskeysByUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountPasskeysByUserRow
	for rows.Next() {
		var i CountPasskeysByUserRow
		if err := rows.Scan(&i.UserID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWebAuthnCeremony = `-- name: CreateWebAuthnCeremony :exec
INSERT INTO webauthn_ceremonies (id, kind, user_id, name, data, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateWebAuthnCeremonyParams struct {
	ID        []byte
	Kind      string
	UserID    *int64
	Name      *string
	Data      []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateWebAuthnCeremony(ctx context.Context, arg CreateWebAuthnCeremonyParams) error {
	_, err := q.db.Exec(ctx, createWebAuthnCeremony,
		arg.ID,
		arg.Kind,
		arg.UserID,
		arg.Name,
		arg.Data,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredWebAuthnCeremonies = `-- name: DeleteExpiredWebAuthnCeremonies :exec
DELETE FROM webauthn_ceremonies WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredWebAuthnCeremonies(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredWebAuthnCeremonies)
	return err
}

const deletePasskey = `-- name: DeletePasskey :one
DELETE FROM passkeys WHERE id = $1 AND user_id = $2 RETURNING name, credential_id
`

type DeletePasskeyParams struct {
	ID     int64
	UserID int64
}

type DeletePasskeyRow struct {
	Name         string
	CredentialID []byte
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) (DeletePasskeyRow, error) {
	row := q.db.QueryRow(ctx, deletePasskey, arg.ID, arg.UserID)
	var i DeletePasskeyRow
	err := row.Scan(&i.Name, &i.CredentialID)
	return i, err
}

const deleteUserPasskeys = `-- name: DeleteUserPasskeys :execrows
DELETE FROM passkeys WHERE user_id = $1
`

func (q *Queries) DeleteUserPasskeys(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserPasskeys, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserWebAuthnCeremonies = `-- name: DeleteUserWebAuthnCeremonies :exec
DELETE FROM webauthn_ceremonies WHERE user_id = $1
`

func (q *Queries) DeleteUserWebAuthnCeremonies(ctx context.Context, userID *int64) error {
	_, err := q.db.Exec(ctx, deleteUserWebAuthnCeremonies, userID)
	return err
}

const insertPasskey = `-- name: InsertPasskey :exec
INSERT INTO passkeys (user_id, credential_id, name, credential) VALUES ($1, $2, $3, $4)
`

type InsertPasskeyParams struct {
	UserID       int64
	CredentialID []byte
	Name         string
	Credential   []byte
}

func (q *Queries) InsertPasskey(ctx context.Context, arg InsertPasskeyParams) error {
	_, err := q.db.Exec(ctx, insertPasskey,
		arg.UserID,
		arg.CredentialID,
		arg.Name,
		arg.Credential,
	)
	return err
}

const listPasskeys = `-- name: ListPasskeys :many
SELECT id, user_id, credential_id, name, credential, created_at, last_used_at FROM passkeys WHERE user_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListPasskeys(ctx context.Context, userID int64) ([]Passkey, error) {
	rows, err := q.db.Query(ctx, listPasskeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passkey
	for rows.Next() {
		var i Passkey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.Name,
			&i.Credential,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPasskey = `-- name: LockPasskey :one
SELECT id, user_id, credential_id, name, credential, created_at, last_used_at FROM passkeys WHERE credential_id = $1 FOR UPDATE
`

// The row stays locked until the transaction ends, so concurrent logins
// with the same passkey see each other's sign count.
func (q *Queries) LockPasskey(ctx context.Context, credentialID []byte) (Passkey, error) {
	row := q.db.QueryRow(ctx, lockPasskey, credentialID)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.Name,
		&i.Credential,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const passkeyOwner = `-- name: PasskeyOwner :one
SELECT user_id FROM passkeys WHERE credential_id = $1
`

func (q *Queries) PasskeyOwner(ctx context.Context, credentialID []byte) (int64, error) {
	row := q.db.QueryRow(ctx, passkeyOwner, credentialID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const setWebAuthnHandle = `-- name: SetWebAuthnHandle :exec
UPDATE users SET webauthn_handle = $2 WHERE id = $1 AND webauthn_handle IS NULL
`

type SetWebAuthnHandleParams struct {
	ID             int64
	WebauthnHandle []byte
}

func (q *Queries) SetWebAuthnHandle(ctx context.Context, arg SetWebAuthnHandleParams) error {
	_, err := q.db.Exec(ctx, setWebAuthnHandle, arg.ID, arg.WebauthnHandle)
	return err
}

const takeWebAuthnCeremony = `-- name: TakeWebAuthnCeremony :one
DELETE FROM webauthn_ceremonies WHERE id = $1 AND kind = $2 AND expires_at > now()
RETURNING id, kind, user_id, name, data, created_at, expires_at
`

type TakeWebAuthnCeremonyParams struct {
	ID   []byte
	Kind string
}

// Uses up a ceremony that has not expired.
func (q *Queries) TakeWebAuthnCeremony(ctx context.Context, arg TakeWebAuthnCeremonyParams) (WebauthnCeremony, error) {
	row := q.db.QueryRow(ctx, takeWebAuthnCeremony, arg.ID, arg.Kind)
	var i WebauthnCeremony
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.Name,
		&i.Data,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updatePasskeyUse = `-- name: UpdatePasskeyUse :exec
UPDATE passkeys SET credential = $2, last_used_at = now() WHERE id = $1
`

type UpdatePasskeyUseParams struct {
	ID         int64
	Credential []byte
}

func (q *Queries) UpdatePasskeyUse(ctx context.Context, arg UpdatePasskeyUseParams) error {
	_, err := q.db.Exec(ctx, updatePasskeyUse, arg.ID, arg.Credential)
	return err
}
