// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconcile.sql

package db

import (
	"context"
	"time"
)

const listAccountFolderStates = `-- name: ListAccountFolderStates :many
SELECT id, name, last_reconciled_at FROM folders WHERE account_id = $1 ORDER BY name
`

type ListAccountFolderStatesRow struct {
	ID               int64
	Name             string
	LastReconciledAt *time.Time
}

func (q *Queries) ListAccountFolderStates(ctx context.Context, accountID int64) ([]ListAccountFolderStatesRow, error) {
	rows, err := q.db.Query(ctx, listAccountFolderStates, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountFolderStatesRow
	for rows.Next() {
		var i ListAccountFolderStatesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.LastReconciledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFolderForReconcile = `-- name: LockFolderForReconcile :one

SELECT uidvalidity, last_uid, last_reconciled_at FROM folders WHERE id = $1 FOR UPDATE
`

type LockFolderForReconcileRow struct {
	Uidvalidity      int64
	LastUid          int64
	LastReconciledAt *time.Time
}

// Reconcile: compare the archive's locations with what the server lists.
// Called while holding the account's sync lock.
func (q *Queries) LockFolderForReconcile(ctx context.Context, id int64) (LockFolderForReconcileRow, error) {
	row := q.db.QueryRow(ctx, lockFolderForReconcile, id)
	var i LockFolderForReconcileRow
	err := row.Scan(&i.Uidvalidity, &i.LastUid, &i.LastReconciledAt)
	return i, err
}

const markFolderVanished = `-- name: MarkFolderVanished :one
WITH gone AS (
    UPDATE message_locations l
    SET gone_at = now(), last_seen_at = GREATEST(l.last_seen_at, $1::timestamptz)
    WHERE l.folder_id = $2 AND l.gone_at IS NULL
    RETURNING 1
),
done AS (
    UPDATE folders SET last_reconciled_at = now() WHERE id = $2 RETURNING 1
)
SELECT (SELECT count(*) FROM gone)::bigint AS gone, (SELECT count(*) FROM done)::bigint AS done
`

type MarkFolderVanishedParams struct {
	PrevReconciledAt *time.Time
	FolderID         int64
}

type MarkFolderVanishedRow struct {
	Gone int64
	Done int64
}

// A folder the server no longer lists: all its locations are gone.
func (q *Queries) MarkFolderVanished(ctx context.Context, arg MarkFolderVanishedParams) (MarkFolderVanishedRow, error) {
	row := q.db.QueryRow(ctx, markFolderVanished, arg.PrevReconciledAt, arg.FolderID)
	var i MarkFolderVanishedRow
	err := row.Scan(&i.Gone, &i.Done)
	return i, err
}

const reconcileFolder = `-- name: ReconcileFolder :one
WITH listed AS MATERIALIZED (
    -- Two unnests in the select list are zipped (same length, from Go).
    SELECT u.uid, string_to_array(u.flags, ' ') AS flags
    FROM (SELECT unnest($1::bigint[]) AS uid, unnest($2::text[]) AS flags) u
),
cur AS MATERIALIZED (
    SELECT l.id, l.gone_at, l.flags, s.uid IS NOT NULL AS listed, s.flags AS new_flags
    FROM message_locations l
    LEFT JOIN listed s ON s.uid = l.uid
    WHERE l.folder_id = $3 AND l.uidvalidity = $4 AND l.uid <= $5
),
gone AS (
    UPDATE message_locations l
    SET gone_at = now(), last_seen_at = GREATEST(l.last_seen_at, $6::timestamptz)
    FROM cur c
    WHERE l.id = c.id AND NOT c.listed AND c.gone_at IS NULL
    RETURNING 1
),
back AS (
    UPDATE message_locations l
    SET gone_at = NULL, last_seen_at = now(), flags = c.new_flags
    FROM cur c
    WHERE l.id = c.id AND c.listed AND c.gone_at IS NOT NULL
    RETURNING 1
),
changed AS (
    UPDATE message_locations l
    SET flags = c.new_flags
    FROM cur c
    WHERE l.id = c.id AND c.listed AND c.gone_at IS NULL
      -- Rows stored before \Recent was dropped keep it until a real change.
      AND NOT (array_remove(c.flags, '\Recent') @> c.new_flags AND array_remove(c.flags, '\Recent') <@ c.new_flags)
    RETURNING 1
),
superseded AS (
    UPDATE message_locations l
    SET gone_at = now(), last_seen_at = GREATEST(l.last_seen_at, $6::timestamptz)
    WHERE l.folder_id = $3 AND l.uidvalidity <> $4 AND l.gone_at IS NULL
    RETURNING 1
),
done AS (
    UPDATE folders SET last_reconciled_at = now() WHERE id = $3 RETURNING 1
)
SELECT (SELECT count(*) FROM cur WHERE cur.gone_at IS NULL)::bigint AS present_before,
       (SELECT count(*) FROM gone)::bigint AS gone,
       (SELECT count(*) FROM superseded)::bigint AS superseded,
       (SELECT count(*) FROM back)::bigint AS back,
       (SELECT count(*) FROM changed)::bigint AS changed,
       (SELECT count(*) FROM done)::bigint AS done
`

type ReconcileFolderParams struct {
	Uids             []int64
	Flags            []string
	FolderID         int64
	Uidvalidity      int64
	LastUid          int64
	PrevReconciledAt *time.Time
}

type ReconcileFolderRow struct {
	PresentBefore int64
	Gone          int64
	Superseded    int64
	Back          int64
	Changed       int64
	Done          int64
}

// One statement for the whole folder. The server's UIDs and flags (flags
// joined by spaces; IMAP flags are atoms without spaces) are hashed once
// and joined with the folder's current locations. Only rows that change
// are written: locations missing on the server become gone, gone ones that
// are listed again come back, and listed ones get their flags when they
// differ as a set. Locations from an older UIDVALIDITY are gone too: the
// rescan in this run stored a new location for every message still there.
func (q *Queries) ReconcileFolder(ctx context.Context, arg ReconcileFolderParams) (ReconcileFolderRow, error) {
	row := q.db.QueryRow(ctx, reconcileFolder,
		arg.Uids,
		arg.Flags,
		arg.FolderID,
		arg.Uidvalidity,
		arg.LastUid,
		arg.PrevReconciledAt,
	)
	var i ReconcileFolderRow
	err := row.Scan(
		&i.PresentBefore,
		&i.Gone,
		&i.Superseded,
		&i.Back,
		&i.Changed,
		&i.Done,
	)
	return i, err
}

const reconcileStates = `-- name: ReconcileStates :many
SELECT a.id,
       (SELECT count(DISTINCT l.message_sha256) FROM message_locations l JOIN folders f ON f.id = l.folder_id
        WHERE f.account_id = a.id AND l.gone_at IS NOT NULL
          AND NOT EXISTS (
              SELECT 1 FROM message_locations p JOIN folders pf ON pf.id = p.folder_id
              WHERE p.message_sha256 = l.message_sha256 AND pf.account_id = a.id AND p.gone_at IS NULL)
       ) AS gone,
       (SELECT f.last_reconciled_at FROM folders f WHERE f.account_id = a.id AND f.last_reconciled_at IS NOT NULL
        ORDER BY f.last_reconciled_at DESC LIMIT 1) AS last_reconciled_at
FROM accounts a
WHERE a.owner_id = $1::bigint
`

type ReconcileStatesRow struct {
	ID               int64
	Gone             int64
	LastReconciledAt *time.Time
}

// Per account of a user: messages whose locations in the account are all
// gone from the server, and the latest reconcile of any of its folders.
func (q *Queries) ReconcileStates(ctx context.Context, owner int64) ([]ReconcileStatesRow, error) {
	rows, err := q.db.Query(ctx, reconcileStates, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReconcileStatesRow
	for rows.Next() {
		var i ReconcileStatesRow
		if err := rows.Scan(&i.ID, &i.Gone, &i.LastReconciledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
