// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
	"time"
)

const countThreadMatches = `-- name: CountThreadMatches :many
SELECT COALESCE(t.thread_id, t.sha256)::text AS thread_key, count(*)::bigint AS matches
FROM messages t
WHERE COALESCE(t.thread_id, t.sha256) = ANY($1::text[])
  AND
  -- filters:begin (keep all copies equal; TestSearchFilterCopies checks)
  ($2::text IS NULL
   OR t.search @@ (websearch_to_tsquery('simple', $2::text) ||
                    websearch_to_tsquery('german', $2::text) ||
                    websearch_to_tsquery('english', $2::text))
   OR t.subject ILIKE $3::text
   OR t.from_addr ILIKE $3::text)
  -- Only messages found in one of the user's accounts.
  AND EXISTS (
       SELECT 1 FROM message_locations l
       JOIN folders f ON f.id = l.folder_id
       JOIN accounts a ON a.id = f.account_id
       WHERE l.message_sha256 = t.sha256
         AND a.owner_id = $4::bigint
         AND ($5::text IS NULL OR a.name = $5::text)
         AND ($6::text IS NULL OR f.name = $6::text))
  -- Filters on single fields. Recipients and attachment names are only
  -- found here, not by the full-text query.
  AND ($7::text IS NULL OR t.from_addr ILIKE $7::text)
  AND ($8::text IS NULL
       OR (coalesce(t.to_addr, '') || E'\n' || coalesce(t.cc_addr, '')) ILIKE $8::text)
  AND ($9::text IS NULL OR t.attachment_names ILIKE $9::text)
  AND (NOT $10::boolean OR t.has_attachment)
  AND ($11::text IS NULL OR COALESCE(t.thread_id, t.sha256) = $11::text)
  AND ($12::timestamptz IS NULL OR t.sort_at >= $12::timestamptz)
  AND ($13::timestamptz IS NULL OR t.sort_at < $13::timestamptz)
  -- Only in the archive: the user's IMAP locations (of the account, if
  -- given) are all gone from the server. Import accounts say nothing about
  -- servers, and removed accounts are never reconciled, so they count as
  -- present. Starts from the few gone locations (message_locations_gone_idx).
  AND (NOT $14::boolean OR t.sha256 IN (
       SELECT g.message_sha256 FROM message_locations g
       JOIN folders gf ON gf.id = g.folder_id
       JOIN accounts ga ON ga.id = gf.account_id
       WHERE g.gone_at IS NOT NULL
         AND ga.owner_id = $4::bigint AND ga.kind = 'imap'
         AND ($5::text IS NULL OR ga.name = $5::text)
         AND NOT EXISTS (
             SELECT 1 FROM message_locations p
             JOIN folders pf ON pf.id = p.folder_id
             JOIN accounts pa ON pa.id = pf.account_id
             WHERE p.message_sha256 = g.message_sha256 AND p.gone_at IS NULL
               AND pa.owner_id = $4::bigint AND pa.kind = 'imap'
               AND ($5::text IS NULL OR pa.name = $5::text))))
  -- filters:end
GROUP BY 1
`

type CountThreadMatchesParams struct {
	ThreadKeys        []string
	Query             *string
	Pattern           *string
	Owner             int64
	Account           *string
	Folder            *string
	FromPattern       *string
	ToPattern         *string
	AttachmentPattern *string
	HasAttachment     bool
	Thread            *string
	After             *time.Time
	Before            *time.Time
	Gone              bool
}

type CountThreadMatchesRow struct {
	ThreadKey string
	Matches   int64
}

// The number of messages per thread that match the filters, for the rows
// of one SearchThreads page.
func (q *Queries) CountThreadMatches(ctx context.Context, arg CountThreadMatchesParams) ([]CountThreadMatchesRow, error) {
	rows, err := q.db.Query(ctx, countThreadMatches,
		arg.ThreadKeys,
		arg.Query,
		arg.Pattern,
		arg.Owner,
		arg.Account,
		arg.Folder,
		arg.FromPattern,
		arg.ToPattern,
		arg.AttachmentPattern,
		arg.HasAttachment,
		arg.Thread,
		arg.After,
		arg.Before,
		arg.Gone,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountThreadMatchesRow
	for rows.Next() {
		var i CountThreadMatchesRow
		if err := rows.Scan(&i.ThreadKey, &i.Matches); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageSummary = `-- name: GetMessageSummary :one
SELECT m.sha256, m.size, m.message_id, m.subject, m.from_addr, m.sent_at, m.sort_at, m.stored_path,
       m.in_reply_to, COALESCE(m.thread_id, m.sha256)::text AS thread_key
FROM messages m
WHERE m.sha256 = $1
  AND EXISTS (
      SELECT 1 FROM message_locations l
      JOIN folders f ON f.id = l.folder_id
      JOIN accounts a ON a.id = f.account_id
      WHERE l.message_sha256 = m.sha256 AND a.owner_id = $2::bigint)
`

type GetMessageSummaryParams struct {
	Sha256 string
	Owner  int64
}

type GetMessageSummaryRow struct {
	Sha256     string
	Size       int64
	MessageID  *string
	Subject    *string
	FromAddr   *string
	SentAt     *time.Time
	SortAt     *time.Time
	StoredPath string
	InReplyTo  *string
	ThreadKey  string
}

// Only if the message was found in one of the user's accounts.
func (q *Queries) GetMessageSummary(ctx context.Context, arg GetMessageSummaryParams) (GetMessageSummaryRow, error) {
	row := q.db.QueryRow(ctx, getMessageSummary, arg.Sha256, arg.Owner)
	var i GetMessageSummaryRow
	err := row.Scan(
		&i.Sha256,
		&i.Size,
		&i.MessageID,
		&i.Subject,
		&i.FromAddr,
		&i.SentAt,
		&i.SortAt,
		&i.StoredPath,
		&i.InReplyTo,
		&i.ThreadKey,
	)
	return i, err
}

const listFolderCounts = `-- name: ListFolderCounts :many
SELECT a.name AS account, a.enabled, (a.removed_at IS NOT NULL)::boolean AS removed, a.kind,
       f.name AS folder,
       (SELECT count(*) FROM (
            SELECT DISTINCT l.message_sha256 FROM message_locations l WHERE l.folder_id = f.id) d
       )::bigint AS messages,
       f.last_synced_at, f.last_reconciled_at
FROM accounts a
LEFT JOIN folders f ON f.account_id = a.id
WHERE a.owner_id = $1::bigint
ORDER BY a.name, f.name
`

type ListFolderCountsRow struct {
	Account          string
	Enabled          bool
	Removed          bool
	Kind             string
	Folder           *string
	Messages         int64
	LastSyncedAt     *time.Time
	LastReconciledAt *time.Time
}

// The number of distinct messages per folder, like the folder's message
// list: a message with an old and a new location (after a UIDVALIDITY
// change) counts once. The subquery per folder uses
// message_locations_folder_sha_idx; a count(DISTINCT) over the grouped join
// is about 20 times slower on large archives.
func (q *Queries) ListFolderCounts(ctx context.Context, owner int64) ([]ListFolderCountsRow, error) {
	rows, err := q.db.Query(ctx, listFolderCounts, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFolderCountsRow
	for rows.Next() {
		var i ListFolderCountsRow
		if err := rows.Scan(
			&i.Account,
			&i.Enabled,
			&i.Removed,
			&i.Kind,
			&i.Folder,
			&i.Messages,
			&i.LastSyncedAt,
			&i.LastReconciledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT a.name AS account, f.name AS folder, l.uid, l.flags, l.internal_date,
       (l.uidvalidity <> f.uidvalidity)::boolean AS superseded, l.gone_at,
       -- A present location was seen at the folder's last reconcile.
       (CASE WHEN l.gone_at IS NULL AND l.uidvalidity = f.uidvalidity
             THEN GREATEST(l.last_seen_at, f.last_reconciled_at)
             ELSE l.last_seen_at END)::timestamptz AS last_seen_at
FROM message_locations l
JOIN folders f ON f.id = l.folder_id
JOIN accounts a ON a.id = f.account_id
WHERE l.message_sha256 = $1 AND a.owner_id = $2::bigint
ORDER BY superseded, a.name, f.name
`

type ListLocationsParams struct {
	Sha256 string
	Owner  int64
}

type ListLocationsRow struct {
	Account      string
	Folder       string
	Uid          int64
	Flags        []string
	InternalDate *time.Time
	Superseded   bool
	GoneAt       *time.Time
	LastSeenAt   time.Time
}

// The user's own locations of a message, current ones first. A location is
// superseded when the folder's UIDVALIDITY changed since it was stored: the
// server renumbered the folder, and the rescan added a new location for
// every message still there. Superseded locations stay as history.
func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]ListLocationsRow, error) {
	rows, err := q.db.Query(ctx, listLocations, arg.Sha256, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationsRow
	for rows.Next() {
		var i ListLocationsRow
		if err := rows.Scan(
			&i.Account,
			&i.Folder,
			&i.Uid,
			&i.Flags,
			&i.InternalDate,
			&i.Superseded,
			&i.GoneAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessages = `-- name: SearchMessages :many

SELECT m.sha256, m.size, m.subject, m.from_addr, m.sent_at, m.sort_at, m.has_attachment,
       CASE
           WHEN $1::text IS NULL THEN left(coalesce(m.body_text, ''), 240)
           ELSE ts_headline('german', coalesce(m.body_text, ''),
                    websearch_to_tsquery('simple', $1::text) ||
                    websearch_to_tsquery('german', $1::text) ||
                    websearch_to_tsquery('english', $1::text),
                    'MaxFragments=1, MaxWords=30, MinWords=12, StartSel=' || chr(57344) || ', StopSel=' || chr(57345))
       END::text AS snippet
FROM messages m
WHERE
  -- filters:begin (keep all copies equal; TestSearchFilterCopies checks)
  ($1::text IS NULL
   OR m.search @@ (websearch_to_tsquery('simple', $1::text) ||
                    websearch_to_tsquery('german', $1::text) ||
                    websearch_to_tsquery('english', $1::text))
   OR m.subject ILIKE $2::text
   OR m.from_addr ILIKE $2::text)
  -- Only messages found in one of the user's accounts.
  AND EXISTS (
       SELECT 1 FROM message_locations l
       JOIN folders f ON f.id = l.folder_id
       JOIN accounts a ON a.id = f.account_id
       WHERE l.message_sha256 = m.sha256
         AND a.owner_id = $3::bigint
         AND ($4::text IS NULL OR a.name = $4::text)
         AND ($5::text IS NULL OR f.name = $5::text))
  -- Filters on single fields. Recipients and attachment names are only
  -- found here, not by the full-text query.
  AND ($6::text IS NULL OR m.from_addr ILIKE $6::text)
  AND ($7::text IS NULL
       OR (coalesce(m.to_addr, '') || E'\n' || coalesce(m.cc_addr, '')) ILIKE $7::text)
  AND ($8::text IS NULL OR m.attachment_names ILIKE $8::text)
  AND (NOT $9::boolean OR m.has_attachment)
  AND ($10::text IS NULL OR COALESCE(m.thread_id, m.sha256) = $10::text)
  AND ($11::timestamptz IS NULL OR m.sort_at >= $11::timestamptz)
  AND ($12::timestamptz IS NULL OR m.sort_at < $12::timestamptz)
  -- Only in the archive: the user's IMAP locations (of the account, if
  -- given) are all gone from the server. Import accounts say nothing about
  -- servers, and removed accounts are never reconciled, so they count as
  -- present. Starts from the few gone locations (message_locations_gone_idx).
  AND (NOT $13::boolean OR m.sha256 IN (
       SELECT g.message_sha256 FROM message_locations g
       JOIN folders gf ON gf.id = g.folder_id
       JOIN accounts ga ON ga.id = gf.account_id
       WHERE g.gone_at IS NOT NULL
         AND ga.owner_id = $3::bigint AND ga.kind = 'imap'
         AND ($4::text IS NULL OR ga.name = $4::text)
         AND NOT EXISTS (
             SELECT 1 FROM message_locations p
             JOIN folders pf ON pf.id = p.folder_id
             JOIN accounts pa ON pa.id = pf.account_id
             WHERE p.message_sha256 = g.message_sha256 AND p.gone_at IS NULL
               AND pa.owner_id = $3::bigint AND pa.kind = 'imap'
               AND ($4::text IS NULL OR pa.name = $4::text))))
  -- filters:end
  AND ($14::timestamptz IS NULL
       OR (m.sort_at, m.sha256) < ($14::timestamptz, $15::text))
ORDER BY m.sort_at DESC, m.sha256 DESC
LIMIT $16
`

type SearchMessagesParams struct {
	Query             *string
	Pattern           *string
	Owner             int64
	Account           *string
	Folder            *string
	FromPattern       *string
	ToPattern         *string
	AttachmentPattern *string
	HasAttachment     bool
	Thread            *string
	After             *time.Time
	Before            *time.Time
	Gone              bool
	CursorAt          *time.Time
	CursorSha         *string
	RowLimit          int32
}

type SearchMessagesRow struct {
	Sha256        string
	Size          int64
	Subject       *string
	FromAddr      *string
	SentAt        *time.Time
	SortAt        *time.Time
	HasAttachment bool
	Snippet       string
}

// Listing and search for the web API. Results are ordered by date (newest
// first) and paginated with a keyset cursor (sort_at, sha256).
func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages,
		arg.Query,
		arg.Pattern,
		arg.Owner,
		arg.Account,
		arg.Folder,
		arg.FromPattern,
		arg.ToPattern,
		arg.AttachmentPattern,
		arg.HasAttachment,
		arg.Thread,
		arg.After,
		arg.Before,
		arg.Gone,
		arg.CursorAt,
		arg.CursorSha,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMessagesRow
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.Sha256,
			&i.Size,
			&i.Subject,
			&i.FromAddr,
			&i.SentAt,
			&i.SortAt,
			&i.HasAttachment,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchThreads = `-- name: SearchThreads :many
SELECT m.sha256, m.size, m.subject, m.from_addr, m.sent_at, m.sort_at, m.has_attachment,
       CASE
           WHEN $1::text IS NULL THEN left(coalesce(m.body_text, ''), 240)
           ELSE ts_headline('german', coalesce(m.body_text, ''),
                    websearch_to_tsquery('simple', $1::text) ||
                    websearch_to_tsquery('german', $1::text) ||
                    websearch_to_tsquery('english', $1::text),
                    'MaxFragments=1, MaxWords=30, MinWords=12, StartSel=' || chr(57344) || ', StopSel=' || chr(57345))
       END::text AS snippet,
       COALESCE(m.thread_id, m.sha256)::text AS thread_key
FROM messages m
WHERE
  -- filters:begin (keep all copies equal; TestSearchFilterCopies checks)
  ($1::text IS NULL
   OR m.search @@ (websearch_to_tsquery('simple', $1::text) ||
                    websearch_to_tsquery('german', $1::text) ||
                    websearch_to_tsquery('english', $1::text))
   OR m.subject ILIKE $2::text
   OR m.from_addr ILIKE $2::text)
  -- Only messages found in one of the user's accounts.
  AND EXISTS (
       SELECT 1 FROM message_locations l
       JOIN folders f ON f.id = l.folder_id
       JOIN accounts a ON a.id = f.account_id
       WHERE l.message_sha256 = m.sha256
         AND a.owner_id = $3::bigint
         AND ($4::text IS NULL OR a.name = $4::text)
         AND ($5::text IS NULL OR f.name = $5::text))
  -- Filters on single fields. Recipients and attachment names are only
  -- found here, not by the full-text query.
  AND ($6::text IS NULL OR m.from_addr ILIKE $6::text)
  AND ($7::text IS NULL
       OR (coalesce(m.to_addr, '') || E'\n' || coalesce(m.cc_addr, '')) ILIKE $7::text)
  AND ($8::text IS NULL OR m.attachment_names ILIKE $8::text)
  AND (NOT $9::boolean OR m.has_attachment)
  AND ($10::text IS NULL OR COALESCE(m.thread_id, m.sha256) = $10::text)
  AND ($11::timestamptz IS NULL OR m.sort_at >= $11::timestamptz)
  AND ($12::timestamptz IS NULL OR m.sort_at < $12::timestamptz)
  -- Only in the archive: the user's IMAP locations (of the account, if
  -- given) are all gone from the server. Import accounts say nothing about
  -- servers, and removed accounts are never reconciled, so they count as
  -- present. Starts from the few gone locations (message_locations_gone_idx).
  AND (NOT $13::boolean OR m.sha256 IN (
       SELECT g.message_sha256 FROM message_locations g
       JOIN folders gf ON gf.id = g.folder_id
       JOIN accounts ga ON ga.id = gf.account_id
       WHERE g.gone_at IS NOT NULL
         AND ga.owner_id = $3::bigint AND ga.kind = 'imap'
         AND ($4::text IS NULL OR ga.name = $4::text)
         AND NOT EXISTS (
             SELECT 1 FROM message_locations p
             JOIN folders pf ON pf.id = p.folder_id
             JOIN accounts pa ON pa.id = pf.account_id
             WHERE p.message_sha256 = g.message_sha256 AND p.gone_at IS NULL
               AND pa.owner_id = $3::bigint AND pa.kind = 'imap'
               AND ($4::text IS NULL OR pa.name = $4::text))))
  -- filters:end
  AND NOT EXISTS (
      SELECT 1 FROM messages n
      WHERE COALESCE(n.thread_id, n.sha256) = COALESCE(m.thread_id, m.sha256)
        AND (n.sort_at, n.sha256) > (m.sort_at, m.sha256)
        AND
        -- filters:begin (keep all copies equal; TestSearchFilterCopies checks)
        ($1::text IS NULL
         OR n.search @@ (websearch_to_tsquery('simple', $1::text) ||
                          websearch_to_tsquery('german', $1::text) ||
                          websearch_to_tsquery('english', $1::text))
         OR n.subject ILIKE $2::text
         OR n.from_addr ILIKE $2::text)
        -- Only messages found in one of the user's accounts.
        AND EXISTS (
             SELECT 1 FROM message_locations l
             JOIN folders f ON f.id = l.folder_id
             JOIN accounts a ON a.id = f.account_id
             WHERE l.message_sha256 = n.sha256
               AND a.owner_id = $3::bigint
               AND ($4::text IS NULL OR a.name = $4::text)
               AND ($5::text IS NULL OR f.name = $5::text))
        -- Filters on single fields. Recipients and attachment names are only
        -- found here, not by the full-text query.
        AND ($6::text IS NULL OR n.from_addr ILIKE $6::text)
        AND ($7::text IS NULL
             OR (coalesce(n.to_addr, '') || E'\n' || coalesce(n.cc_addr, '')) ILIKE $7::text)
        AND ($8::text IS NULL OR n.attachment_names ILIKE $8::text)
        AND (NOT $9::boolean OR n.has_attachment)
        AND ($10::text IS NULL OR COALESCE(n.thread_id, n.sha256) = $10::text)
        AND ($11::timestamptz IS NULL OR n.sort_at >= $11::timestamptz)
        AND ($12::timestamptz IS NULL OR n.sort_at < $12::timestamptz)
        -- Only in the archive: the user's IMAP locations (of the account, if
        -- given) are all gone from the server. Import accounts say nothing about
        -- servers, and removed accounts are never reconciled, so they count as
        -- present. Starts from the few gone locations (message_locations_gone_idx).
        AND (NOT $13::boolean OR n.sha256 IN (
             SELECT g.message_sha256 FROM message_locations g
             JOIN folders gf ON gf.id = g.folder_id
             JOIN accounts ga ON ga.id = gf.account_id
             WHERE g.gone_at IS NOT NULL
               AND ga.owner_id = $3::bigint AND ga.kind = 'imap'
               AND ($4::text IS NULL OR ga.name = $4::text)
               AND NOT EXISTS (
                   SELECT 1 FROM message_locations p
                   JOIN folders pf ON pf.id = p.folder_id
                   JOIN accounts pa ON pa.id = pf.account_id
                   WHERE p.message_sha256 = g.message_sha256 AND p.gone_at IS NULL
                     AND pa.owner_id = $3::bigint AND pa.kind = 'imap'
                     AND ($4::text IS NULL OR pa.name = $4::text))))
        -- filters:end
  )
  AND ($14::timestamptz IS NULL
       OR (m.sort_at, m.sha256) < ($14::timestamptz, $15::text))
ORDER BY m.sort_at DESC, m.sha256 DESC
LIMIT $16
`

type SearchThreadsParams struct {
	Query             *string
	Pattern           *string
	Owner             int64
	Account           *string
	Folder            *string
	FromPattern       *string
	ToPattern         *string
	AttachmentPattern *string
	HasAttachment     bool
	Thread            *string
	After             *time.Time
	Before            *time.Time
	Gone              bool
	CursorAt          *time.Time
	CursorSha         *string
	RowLimit          int32
}

type SearchThreadsRow struct {
	Sha256        string
	Size          int64
	Subject       *string
	FromAddr      *string
	SentAt        *time.Time
	SortAt        *time.Time
	HasAttachment bool
	Snippet       string
	ThreadKey     string
}

// One row per thread (the thread key COALESCE(thread_id, sha256)): the
// newest message of the thread that matches the filters. Walking the date
// order and skipping messages with a newer match in their thread stops
// after row_limit rows, like SearchMessages.
func (q *Queries) SearchThreads(ctx context.Context, arg SearchThreadsParams) ([]SearchThreadsRow, error) {
	rows, err := q.db.Query(ctx, searchThreads,
		arg.Query,
		arg.Pattern,
		arg.Owner,
		arg.Account,
		arg.Folder,
		arg.FromPattern,
		arg.ToPattern,
		arg.AttachmentPattern,
		arg.HasAttachment,
		arg.Thread,
		arg.After,
		arg.Before,
		arg.Gone,
		arg.CursorAt,
		arg.CursorSha,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchThreadsRow
	for rows.Next() {
		var i SearchThreadsRow
		if err := rows.Scan(
			&i.Sha256,
			&i.Size,
			&i.Subject,
			&i.FromAddr,
			&i.SentAt,
			&i.SortAt,
			&i.HasAttachment,
			&i.Snippet,
			&i.ThreadKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
