// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
	"time"
)

const getMessageSummary = `-- name: GetMessageSummary :one
SELECT sha256, size, message_id, subject, from_addr, sent_at, sort_at, stored_path
FROM messages WHERE sha256 = $1
`

type GetMessageSummaryRow struct {
	Sha256     string
	Size       int64
	MessageID  *string
	Subject    *string
	FromAddr   *string
	SentAt     *time.Time
	SortAt     *time.Time
	StoredPath string
}

func (q *Queries) GetMessageSummary(ctx context.Context, sha256 string) (GetMessageSummaryRow, error) {
	row := q.db.QueryRow(ctx, getMessageSummary, sha256)
	var i GetMessageSummaryRow
	err := row.Scan(
		&i.Sha256,
		&i.Size,
		&i.MessageID,
		&i.Subject,
		&i.FromAddr,
		&i.SentAt,
		&i.SortAt,
		&i.StoredPath,
	)
	return i, err
}

const listFolderCounts = `-- name: ListFolderCounts :many
SELECT a.name AS account, a.enabled, (a.removed_at IS NOT NULL)::boolean AS removed,
       f.name AS folder, count(l.id) AS messages, f.last_synced_at
FROM accounts a
LEFT JOIN folders f ON f.account_id = a.id
LEFT JOIN message_locations l ON l.folder_id = f.id
GROUP BY a.name, a.enabled, a.removed_at, f.name, f.last_synced_at
ORDER BY a.name, f.name
`

type ListFolderCountsRow struct {
	Account      string
	Enabled      bool
	Removed      bool
	Folder       *string
	Messages     int64
	LastSyncedAt *time.Time
}

func (q *Queries) ListFolderCounts(ctx context.Context) ([]ListFolderCountsRow, error) {
	rows, err := q.db.Query(ctx, listFolderCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFolderCountsRow
	for rows.Next() {
		var i ListFolderCountsRow
		if err := rows.Scan(
			&i.Account,
			&i.Enabled,
			&i.Removed,
			&i.Folder,
			&i.Messages,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT a.name AS account, f.name AS folder, l.uid, l.flags, l.internal_date
FROM message_locations l
JOIN folders f ON f.id = l.folder_id
JOIN accounts a ON a.id = f.account_id
WHERE l.message_sha256 = $1
ORDER BY a.name, f.name
`

type ListLocationsRow struct {
	Account      string
	Folder       string
	Uid          int64
	Flags        []string
	InternalDate *time.Time
}

func (q *Queries) ListLocations(ctx context.Context, messageSha256 string) ([]ListLocationsRow, error) {
	rows, err := q.db.Query(ctx, listLocations, messageSha256)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationsRow
	for rows.Next() {
		var i ListLocationsRow
		if err := rows.Scan(
			&i.Account,
			&i.Folder,
			&i.Uid,
			&i.Flags,
			&i.InternalDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessages = `-- name: SearchMessages :many

SELECT m.sha256, m.size, m.subject, m.from_addr, m.sent_at, m.sort_at,
       CASE
           WHEN $1::text IS NULL THEN left(coalesce(m.body_text, ''), 240)
           ELSE ts_headline('german', coalesce(m.body_text, ''),
                    websearch_to_tsquery('simple', $1::text) ||
                    websearch_to_tsquery('german', $1::text) ||
                    websearch_to_tsquery('english', $1::text),
                    'MaxFragments=1, MaxWords=30, MinWords=12, StartSel=' || chr(57344) || ', StopSel=' || chr(57345))
       END::text AS snippet
FROM messages m
WHERE ($1::text IS NULL
       OR m.search @@ (websearch_to_tsquery('simple', $1::text) ||
                       websearch_to_tsquery('german', $1::text) ||
                       websearch_to_tsquery('english', $1::text))
       OR m.subject ILIKE $2::text
       OR m.from_addr ILIKE $2::text)
  AND ($3::text IS NULL AND $4::text IS NULL
       OR EXISTS (
           SELECT 1 FROM message_locations l
           JOIN folders f ON f.id = l.folder_id
           JOIN accounts a ON a.id = f.account_id
           WHERE l.message_sha256 = m.sha256
             AND ($3::text IS NULL OR a.name = $3::text)
             AND ($4::text IS NULL OR f.name = $4::text)))
  AND ($5::timestamptz IS NULL OR m.sort_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR m.sort_at < $6::timestamptz)
  AND ($7::timestamptz IS NULL
       OR (m.sort_at, m.sha256) < ($7::timestamptz, $8::text))
ORDER BY m.sort_at DESC, m.sha256 DESC
LIMIT $9
`

type SearchMessagesParams struct {
	Query     *string
	Pattern   *string
	Account   *string
	Folder    *string
	After     *time.Time
	Before    *time.Time
	CursorAt  *time.Time
	CursorSha *string
	RowLimit  int32
}

type SearchMessagesRow struct {
	Sha256   string
	Size     int64
	Subject  *string
	FromAddr *string
	SentAt   *time.Time
	SortAt   *time.Time
	Snippet  string
}

// Listing and search for the web API. Results are ordered by date (newest
// first) and paginated with a keyset cursor (sort_at, sha256).
func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages,
		arg.Query,
		arg.Pattern,
		arg.Account,
		arg.Folder,
		arg.After,
		arg.Before,
		arg.CursorAt,
		arg.CursorSha,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMessagesRow
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.Sha256,
			&i.Size,
			&i.Subject,
			&i.FromAddr,
			&i.SentAt,
			&i.SortAt,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
