// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
	"time"
)

const getMessageSummary = `-- name: GetMessageSummary :one
SELECT m.sha256, m.size, m.message_id, m.subject, m.from_addr, m.sent_at, m.sort_at, m.stored_path
FROM messages m
WHERE m.sha256 = $1
  AND EXISTS (
      SELECT 1 FROM message_locations l
      JOIN folders f ON f.id = l.folder_id
      JOIN accounts a ON a.id = f.account_id
      WHERE l.message_sha256 = m.sha256 AND a.owner_id = $2::bigint)
`

type GetMessageSummaryParams struct {
	Sha256 string
	Owner  int64
}

type GetMessageSummaryRow struct {
	Sha256     string
	Size       int64
	MessageID  *string
	Subject    *string
	FromAddr   *string
	SentAt     *time.Time
	SortAt     *time.Time
	StoredPath string
}

// Only if the message was found in one of the user's accounts.
func (q *Queries) GetMessageSummary(ctx context.Context, arg GetMessageSummaryParams) (GetMessageSummaryRow, error) {
	row := q.db.QueryRow(ctx, getMessageSummary, arg.Sha256, arg.Owner)
	var i GetMessageSummaryRow
	err := row.Scan(
		&i.Sha256,
		&i.Size,
		&i.MessageID,
		&i.Subject,
		&i.FromAddr,
		&i.SentAt,
		&i.SortAt,
		&i.StoredPath,
	)
	return i, err
}

const listFolderCounts = `-- name: ListFolderCounts :many
SELECT a.name AS account, a.enabled, (a.removed_at IS NOT NULL)::boolean AS removed, a.kind,
       f.name AS folder,
       (SELECT count(*) FROM (
            SELECT DISTINCT l.message_sha256 FROM message_locations l WHERE l.folder_id = f.id) d
       )::bigint AS messages,
       f.last_synced_at
FROM accounts a
LEFT JOIN folders f ON f.account_id = a.id
WHERE a.owner_id = $1::bigint
ORDER BY a.name, f.name
`

type ListFolderCountsRow struct {
	Account      string
	Enabled      bool
	Removed      bool
	Kind         string
	Folder       *string
	Messages     int64
	LastSyncedAt *time.Time
}

// The number of distinct messages per folder, like the folder's message
// list: a message with an old and a new location (after a UIDVALIDITY
// change) counts once. The subquery per folder uses
// message_locations_folder_sha_idx; a count(DISTINCT) over the grouped join
// is about 20 times slower on large archives.
func (q *Queries) ListFolderCounts(ctx context.Context, owner int64) ([]ListFolderCountsRow, error) {
	rows, err := q.db.Query(ctx, listFolderCounts, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFolderCountsRow
	for rows.Next() {
		var i ListFolderCountsRow
		if err := rows.Scan(
			&i.Account,
			&i.Enabled,
			&i.Removed,
			&i.Kind,
			&i.Folder,
			&i.Messages,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT a.name AS account, f.name AS folder, l.uid, l.flags, l.internal_date,
       (l.uidvalidity <> f.uidvalidity)::boolean AS superseded
FROM message_locations l
JOIN folders f ON f.id = l.folder_id
JOIN accounts a ON a.id = f.account_id
WHERE l.message_sha256 = $1 AND a.owner_id = $2::bigint
ORDER BY superseded, a.name, f.name
`

type ListLocationsParams struct {
	Sha256 string
	Owner  int64
}

type ListLocationsRow struct {
	Account      string
	Folder       string
	Uid          int64
	Flags        []string
	InternalDate *time.Time
	Superseded   bool
}

// The user's own locations of a message, current ones first. A location is
// superseded when the folder's UIDVALIDITY changed since it was stored: the
// server renumbered the folder, and the rescan added a new location for
// every message still there. Superseded locations stay as history.
func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]ListLocationsRow, error) {
	rows, err := q.db.Query(ctx, listLocations, arg.Sha256, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationsRow
	for rows.Next() {
		var i ListLocationsRow
		if err := rows.Scan(
			&i.Account,
			&i.Folder,
			&i.Uid,
			&i.Flags,
			&i.InternalDate,
			&i.Superseded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessages = `-- name: SearchMessages :many

SELECT m.sha256, m.size, m.subject, m.from_addr, m.sent_at, m.sort_at, m.has_attachment,
       CASE
           WHEN $1::text IS NULL THEN left(coalesce(m.body_text, ''), 240)
           ELSE ts_headline('german', coalesce(m.body_text, ''),
                    websearch_to_tsquery('simple', $1::text) ||
                    websearch_to_tsquery('german', $1::text) ||
                    websearch_to_tsquery('english', $1::text),
                    'MaxFragments=1, MaxWords=30, MinWords=12, StartSel=' || chr(57344) || ', StopSel=' || chr(57345))
       END::text AS snippet
FROM messages m
WHERE ($1::text IS NULL
       OR m.search @@ (websearch_to_tsquery('simple', $1::text) ||
                       websearch_to_tsquery('german', $1::text) ||
                       websearch_to_tsquery('english', $1::text))
       OR m.subject ILIKE $2::text
       OR m.from_addr ILIKE $2::text)
  -- Only messages found in one of the user's accounts.
  AND EXISTS (
           SELECT 1 FROM message_locations l
           JOIN folders f ON f.id = l.folder_id
           JOIN accounts a ON a.id = f.account_id
           WHERE l.message_sha256 = m.sha256
             AND a.owner_id = $3::bigint
             AND ($4::text IS NULL OR a.name = $4::text)
             AND ($5::text IS NULL OR f.name = $5::text))
  -- Filters on single fields. Recipients and attachment names are only
  -- found here, not by the full-text query.
  AND ($6::text IS NULL OR m.from_addr ILIKE $6::text)
  AND ($7::text IS NULL
       OR (coalesce(m.to_addr, '') || E'\n' || coalesce(m.cc_addr, '')) ILIKE $7::text)
  AND ($8::text IS NULL OR m.attachment_names ILIKE $8::text)
  AND (NOT $9::boolean OR m.has_attachment)
  AND ($10::timestamptz IS NULL OR m.sort_at >= $10::timestamptz)
  AND ($11::timestamptz IS NULL OR m.sort_at < $11::timestamptz)
  AND ($12::timestamptz IS NULL
       OR (m.sort_at, m.sha256) < ($12::timestamptz, $13::text))
ORDER BY m.sort_at DESC, m.sha256 DESC
LIMIT $14
`

type SearchMessagesParams struct {
	Query             *string
	Pattern           *string
	Owner             int64
	Account           *string
	Folder            *string
	FromPattern       *string
	ToPattern         *string
	AttachmentPattern *string
	HasAttachment     bool
	After             *time.Time
	Before            *time.Time
	CursorAt          *time.Time
	CursorSha         *string
	RowLimit          int32
}

type SearchMessagesRow struct {
	Sha256        string
	Size          int64
	Subject       *string
	FromAddr      *string
	SentAt        *time.Time
	SortAt        *time.Time
	HasAttachment bool
	Snippet       string
}

// Listing and search for the web API. Results are ordered by date (newest
// first) and paginated with a keyset cursor (sort_at, sha256).
func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages,
		arg.Query,
		arg.Pattern,
		arg.Owner,
		arg.Account,
		arg.Folder,
		arg.FromPattern,
		arg.ToPattern,
		arg.AttachmentPattern,
		arg.HasAttachment,
		arg.After,
		arg.Before,
		arg.CursorAt,
		arg.CursorSha,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMessagesRow
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.Sha256,
			&i.Size,
			&i.Subject,
			&i.FromAddr,
			&i.SentAt,
			&i.SortAt,
			&i.HasAttachment,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
