// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_health.sql

package db

import (
	"context"
	"time"
)

const claimNotifications = `-- name: ClaimNotifications :many
UPDATE account_sync_health h
SET notify_lease = $1, notify_lease_until = now() + make_interval(secs => $2::float8)
FROM accounts a LEFT JOIN users u ON u.id = a.owner_id
WHERE h.account_id = a.id AND h.account_id IN (
    SELECT c.account_id FROM account_sync_health c JOIN accounts ca ON ca.id = c.account_id
    WHERE ca.kind = 'imap' AND ca.enabled AND ca.removed_at IS NULL
      AND ((c.failure_streak >= $3::int AND c.notified_state = 'ok')
        OR (c.failure_streak = 0 AND c.notified_state = 'failing'))
      AND (c.notify_next_at IS NULL OR c.notify_next_at <= now())
      AND (c.notify_lease_until IS NULL OR c.notify_lease_until < now())
    ORDER BY c.account_id
    LIMIT $4
    FOR UPDATE OF c SKIP LOCKED)
RETURNING h.account_id, a.name AS account_name, coalesce(u.name, '')::text AS owner_name, h.failure_streak, h.failing_since,
    h.notified_state, h.notify_attempts, h.notify_first_error_at,
    coalesce((SELECT r.error FROM sync_runs r WHERE r.account_id = h.account_id AND r.finished_at IS NOT NULL
              ORDER BY r.started_at DESC LIMIT 1), '')::text AS last_error
`

type ClaimNotificationsParams struct {
	Lease        []byte
	LeaseSeconds float64
	Threshold    int32
	MaxRows      int32
}

type ClaimNotificationsRow struct {
	AccountID          int64
	AccountName        string
	OwnerName          string
	FailureStreak      int32
	FailingSince       *time.Time
	NotifiedState      string
	NotifyAttempts     int32
	NotifyFirstErrorAt *time.Time
	LastError          string
}

// Leases up to max_rows enabled IMAP accounts with an announcement due: an
// alert (streak reached the threshold, last announced ok) or a recovery
// (streak ended, last announced failing). Rows another notifier holds are
// skipped, so no transition is claimed twice.
func (q *Queries) ClaimNotifications(ctx context.Context, arg ClaimNotificationsParams) ([]ClaimNotificationsRow, error) {
	rows, err := q.db.Query(ctx, claimNotifications,
		arg.Lease,
		arg.LeaseSeconds,
		arg.Threshold,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimNotificationsRow
	for rows.Next() {
		var i ClaimNotificationsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountName,
			&i.OwnerName,
			&i.FailureStreak,
			&i.FailingSince,
			&i.NotifiedState,
			&i.NotifyAttempts,
			&i.NotifyFirstErrorAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFailingByOwner = `-- name: CountFailingByOwner :many
SELECT a.owner_id, count(*) AS failing
FROM accounts a JOIN account_sync_health h ON h.account_id = a.id
WHERE a.kind = 'imap' AND a.enabled AND a.removed_at IS NULL AND a.owner_id IS NOT NULL
  AND h.failure_streak >= $1::int
GROUP BY a.owner_id
`

type CountFailingByOwnerRow struct {
	OwnerID *int64
	Failing int64
}

// Enabled IMAP accounts per owner whose streak reached the threshold.
func (q *Queries) CountFailingByOwner(ctx context.Context, threshold int32) ([]CountFailingByOwnerRow, error) {
	rows, err := q.db.Query(ctx, countFailingByOwner, threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountFailingByOwnerRow
	for rows.Next() {
		var i CountFailingByOwnerRow
		if err := rows.Scan(&i.OwnerID, &i.Failing); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deferNotification = `-- name: DeferNotification :execrows
UPDATE account_sync_health
SET notify_attempts = notify_attempts + 1, notify_next_at = $1::timestamptz, notify_error = $2::text,
    notify_first_error_at = coalesce(notify_first_error_at, now()),
    notify_lease = NULL, notify_lease_until = NULL
WHERE account_id = $3 AND notify_lease = $4
`

type DeferNotificationParams struct {
	NextAt      time.Time
	NotifyError string
	AccountID   int64
	Lease       []byte
}

// A delivery attempt failed: try again at next_at.
func (q *Queries) DeferNotification(ctx context.Context, arg DeferNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deferNotification,
		arg.NextAt,
		arg.NotifyError,
		arg.AccountID,
		arg.Lease,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishNotification = `-- name: FinishNotification :execrows
UPDATE account_sync_health
SET notified_state = $1, notified_at = now(), notify_attempts = 0, notify_next_at = NULL,
    notify_error = NULLIF($2::text, ''), notify_first_error_at = NULL,
    notify_lease = NULL, notify_lease_until = NULL
WHERE account_id = $3 AND notify_lease = $4
`

type FinishNotificationParams struct {
	NotifiedState string
	NotifyError   string
	AccountID     int64
	Lease         []byte
}

// The announcement was delivered (or given up): record it and clear the
// delivery state. Only the notifier holding the lease may do this.
func (q *Queries) FinishNotification(ctx context.Context, arg FinishNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishNotification,
		arg.NotifiedState,
		arg.NotifyError,
		arg.AccountID,
		arg.Lease,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordSyncFailure = `-- name: RecordSyncFailure :exec
INSERT INTO account_sync_health AS h (account_id, failure_streak, failing_since) VALUES ($1, 1, now())
ON CONFLICT (account_id) DO UPDATE SET
    failure_streak = h.failure_streak + 1,
    failing_since = CASE WHEN h.failure_streak = 0 THEN now() ELSE h.failing_since END,
    notify_attempts = CASE WHEN h.failure_streak = 0 THEN 0 ELSE h.notify_attempts END,
    notify_next_at = CASE WHEN h.failure_streak = 0 THEN NULL ELSE h.notify_next_at END,
    notify_error = CASE WHEN h.failure_streak = 0 THEN NULL ELSE h.notify_error END,
    notify_first_error_at = CASE WHEN h.failure_streak = 0 THEN NULL ELSE h.notify_first_error_at END
`

// A failed run extends the streak. The first failure starts a new streak
// and drops a pending recovery message.
func (q *Queries) RecordSyncFailure(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, recordSyncFailure, accountID)
	return err
}

const recordSyncSuccess = `-- name: RecordSyncSuccess :exec
INSERT INTO account_sync_health AS h (account_id, last_success_at) VALUES ($1, now())
ON CONFLICT (account_id) DO UPDATE SET
    failure_streak = 0,
    last_success_at = now(),
    notify_attempts = CASE WHEN h.failure_streak > 0 THEN 0 ELSE h.notify_attempts END,
    notify_next_at = CASE WHEN h.failure_streak > 0 THEN NULL ELSE h.notify_next_at END,
    notify_error = CASE WHEN h.failure_streak > 0 THEN NULL ELSE h.notify_error END,
    notify_first_error_at = CASE WHEN h.failure_streak > 0 THEN NULL ELSE h.notify_first_error_at END
`

// An ok or partial run: the login worked, the streak ends. A pending alert
// is dropped and its delivery state reset.
func (q *Queries) RecordSyncSuccess(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, recordSyncSuccess, accountID)
	return err
}

const syncHealth = `-- name: SyncHealth :many
SELECT a.id, a.name, a.owner_id, a.enabled, a.created_at,
       coalesce(h.failure_streak, 0)::int AS failure_streak, h.failing_since, h.last_success_at,
       coalesce(h.notified_state, 'ok')::text AS notified_state
FROM accounts a LEFT JOIN account_sync_health h ON h.account_id = a.id
WHERE a.kind = 'imap' AND a.removed_at IS NULL
  AND ($1::bigint IS NULL OR a.owner_id = $1::bigint)
ORDER BY a.id
`

type SyncHealthRow struct {
	ID            int64
	Name          string
	OwnerID       *int64
	Enabled       bool
	CreatedAt     time.Time
	FailureStreak int32
	FailingSince  *time.Time
	LastSuccessAt *time.Time
	NotifiedState string
}

// The health of IMAP accounts that are not removed, of all users or one.
func (q *Queries) SyncHealth(ctx context.Context, owner *int64) ([]SyncHealthRow, error) {
	rows, err := q.db.Query(ctx, syncHealth, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncHealthRow
	for rows.Next() {
		var i SyncHealthRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.Enabled,
			&i.CreatedAt,
			&i.FailureStreak,
			&i.FailingSince,
			&i.LastSuccessAt,
			&i.NotifiedState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
