// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_runs.sql

package db

import (
	"context"
	"time"
)

const accountStats = `-- name: AccountStats :many
SELECT a.id, a.name, a.enabled, a.owner_id,
       (SELECT count(*) FROM folders f WHERE f.account_id = a.id) AS folders,
       (SELECT count(*) FROM message_locations l JOIN folders f ON f.id = l.folder_id
        WHERE f.account_id = a.id) AS locations
FROM accounts a
WHERE $1::bigint IS NULL OR a.owner_id = $1::bigint
ORDER BY a.name, a.owner_id
`

type AccountStatsRow struct {
	ID        int64
	Name      string
	Enabled   bool
	OwnerID   *int64
	Folders   int64
	Locations int64
}

// All accounts, or only those of one owner.
func (q *Queries) AccountStats(ctx context.Context, owner *int64) ([]AccountStatsRow, error) {
	rows, err := q.db.Query(ctx, accountStats, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountStatsRow
	for rows.Next() {
		var i AccountStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.OwnerID,
			&i.Folders,
			&i.Locations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failStaleSyncRuns = `-- name: FailStaleSyncRuns :execrows
UPDATE sync_runs SET finished_at = now(), status = 'failed', error = 'interrupted'
WHERE account_id = $1 AND finished_at IS NULL
`

// Runs left "running" by a process that died. Only called while holding the
// account's sync lock, so no other run of the account can be active.
func (q *Queries) FailStaleSyncRuns(ctx context.Context, accountID int64) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleSyncRuns, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishSyncRun = `-- name: FinishSyncRun :execrows
UPDATE sync_runs
SET finished_at = now(), status = $1, messages_fetched = $2,
    messages_new = $3, error = NULLIF($4::text, '')
WHERE id = $5
`

type FinishSyncRunParams struct {
	Status          string
	MessagesFetched int32
	MessagesNew     int32
	Error           string
	ID              int64
}

func (q *Queries) FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishSyncRun,
		arg.Status,
		arg.MessagesFetched,
		arg.MessagesNew,
		arg.Error,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lastSyncRuns = `-- name: LastSyncRuns :many
SELECT DISTINCT ON (account_id) account_id, started_at, finished_at, status,
       messages_fetched, messages_new, error
FROM sync_runs
ORDER BY account_id, started_at DESC
`

type LastSyncRunsRow struct {
	AccountID       int64
	StartedAt       time.Time
	FinishedAt      *time.Time
	Status          string
	MessagesFetched int32
	MessagesNew     int32
	Error           *string
}

// The most recent sync run per account, with counters.
func (q *Queries) LastSyncRuns(ctx context.Context) ([]LastSyncRunsRow, error) {
	rows, err := q.db.Query(ctx, lastSyncRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LastSyncRunsRow
	for rows.Next() {
		var i LastSyncRunsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.MessagesFetched,
			&i.MessagesNew,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startSyncRun = `-- name: StartSyncRun :one
INSERT INTO sync_runs (account_id) VALUES ($1) RETURNING id
`

func (q *Queries) StartSyncRun(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, startSyncRun, accountID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateSyncRunProgress = `-- name: UpdateSyncRunProgress :exec
UPDATE sync_runs SET messages_fetched = $1, messages_new = $2
WHERE id = $3 AND finished_at IS NULL
`

type UpdateSyncRunProgressParams struct {
	MessagesFetched int32
	MessagesNew     int32
	ID              int64
}

func (q *Queries) UpdateSyncRunProgress(ctx context.Context, arg UpdateSyncRunProgressParams) error {
	_, err := q.db.Exec(ctx, updateSyncRunProgress, arg.MessagesFetched, arg.MessagesNew, arg.ID)
	return err
}
